In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files

In [3]:
uploded=files.upload()

Saving StudentsPerformance.csv to StudentsPerformance.csv

In [6]:
df=pd.read_csv("/content/StudentsPerformance.csv")

In [7]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [11]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [12]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [13]:
df.head(11)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52

In [14]:
df.tail(11)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
989,female,group D,some college,free/reduced,completed,67,86,83
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [15]:
df.shape

(1000, 8)

In [19]:
pd.set_option('display.max_rows',1000)

In [20]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

In [21]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [23]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [24]:
max(df.index)

999

In [26]:
min(df.index)

0

In [27]:
len(df)

1000

In [28]:
type(df)

pandas.core.frame.DataFrame

In [29]:
#finding particular column
df['gender']

0      female
1      female
2      female
3        male
4        male
5      female
6      female
7        male
8        male
9      female
10       male
11       male
12     female
13       male
14     female
15     female
16       male
17     female
18       male
19     female
20       male
21     female
22       male
23     female
24       male
25       male
26       male
27     female
28       male
29     female
30     female
31     female
32     female
33       male
34       male
35       male
36     female
37     female
38     female
39       male
40       male
41     female
42     female
43       male
44     female
45       male
46     female
47     female
48     female
49       male
50       male
51       male
52       male
53       male
54     female
55     female
56     female
57       male
58       male
59     female
60       male
61       male
62       male
63     female
64     female
65       male
66       male
67     female
68       male
69     female
70     female
71       male
72     female
73       male
74       male
75       male
76       male
77       male
78     female
79     female
80     female
81       male
82       male
83       male
84       male
85     female
86     female
87     female
88     female
89     female
90     female
91       male
92       male
93       male
94     female
95       male
96       male
97     female
98     female
99     female
100      male
101      male
102    female
103      male
104      male
105    female
106    female
107      male
108    female
109    female
110    female
111      male
112      male
113    female
114    female
115      male
116    female
117    female
118    female
119    female
120    female
121      male
122    female
123      male
124      male
125    female
126      male
127      male
128      male
129    female
130      male
131      male
132      male
133    female
134      male
135      male
136      male
137      male
138    female
139      male
140    female
141    female
142    female
143      male
144      male
145    female
146      male
147      male
148    female
149      male
150      male
151      male
152    female
153      male
154      male
155    female
156    female
157      male
158    female
159      male
160      male
161    female
162      male
163      male
164    female
165    female
166      male
167    female
168    female
169    female
170      male
171      male
172    female
173    female
174    female
175    female
176    female
177    female
178    female
179    female
180      male
181    female
182    female
183    female
184      male
185      male
186      male
187      male
188      male
189    female
190    female
191      male
192    female
193      male
194    female
195      male
196      male
197      male
198    female
199    female
200    female
201    female
202      male
203    female
204      male
205      male
206      male
207      male
208    female
209    female
210      male
211      male
212    female
213      male
214      male
215      male
216    female
217    female
218      male
219      male
220    female
221      male
222    female
223      male
224    female
225    female
226    female
227      male
228      male
229    female
230      male
231      male
232    female
233      male
234      male
235      male
236      male
237    female
238      male
239      male
240      male
241    female
242    female
243      male
244      male
245      male
246      male
247    female
248    female
249      male
250      male
251    female
252    female
253      male
254      male
255    female
256    female
257      male
258    female
259    female
260    female
261      male
262    female
263    female
264      male
265      male
266    female
267    female
268    female
269    female
270      male
271      male
272    female
273    female
274      male
275      male
276    female
277    female
278    female
279      male
280      male
281      male
282    female
283    female
284    female
285      male
286      male
287    female
288      male
289      male
290      male
291      male
292      male
293    female
294      male
295      male
296      male
297      male
298      male
299      male
300      male
301      male
302    female
303      male
304    female
305      male
306      male
307      male
308    female
309    female
310    female
311      male
312      male
313    female
314    female
315      male
316    female
317      male
318      male
319    female
320    female
321    female
322    female
323    female
324    female
325    female
326      male
327      male
328      male
329    female
330      male
331      male
332      male
333      male
334    female
335    female
336      male
337      male
338    female
339    female
340      male
341    female
342    female
343      male
344      male
345    female
346      male
347    female
348      male
349      male
350    female
351      male
352    female
353    female
354    female
355    female
356      male
357    female
358      male
359    female
360    female
361      male
362    female
363    female
364      male
365      male
366      male
367      male
368    female
369    female
370      male
371    female
372      male
373    female
374    female
375      male
376    female
377    female
378    female
379      male
380    female
381      male
382      male
383    female
384    female
385    female
386    female
387    female
388    female
389      male
390      male
391    female
392      male
393      male
394    female
395      male
396    female
397    female
398      male
399      male
400    female
401      male
402    female
403    female
404    female
405    female
406      male
407    female
408    female
409      male
410    female
411      male
412      male
413      male
414    female
415      male
416      male
417      male
418      male
419      male
420    female
421    female
422    female
423    female
424      male
425    female
426      male
427      male
428      male
429      male
430      male
431    female
432      male
433    female
434      male
435      male
436      male
437      male
438      male
439      male
440    female
441    female
442    female
443    female
444      male
445    female
446      male
447      male
448      male
449      male
450    female
451    female
452    female
453      male
454    female
455      male
456    female
457      male
458    female
459      male
460      male
461      male
462    female
463    female
464      male
465    female
466    female
467      male
468    female
469      male
470    female
471    female
472    female
473    female
474    female
475    female
476      male
477      male
478    female
479      male
480      male
481    female
482      male
483      male
484    female
485      male
486      male
487    female
488      male
489      male
490    female
491    female
492    female
493    female
494    female
495      male
496    female
497    female
498    female
499      male
500    female
501    female
502      male
503    female
504    female
505    female
506      male
507      male
508      male
509    female
510      male
511      male
512      male
513    female
514    female
515    female
516    female
517    female
518    female
519    female
520      male
521    female
522      male
523      male
524      male
525      male
526      male
527    female
528    female
529    female
530    female
531    female
532      male
533    female
534      male
535    female
536      male
537    female
538      male
539      male
540      male
541      male
542    female
543    female
544    female
545      male
546    female
547      male
548    female
549      male
550      male
551      male
552    female
553      male
554      male
555    female
556    female
557      male
558    female
559      male
560    female
561    female
562      male
563    female
564      male
565      male
566    female
567    female
568      male
569      male
570      male
571      male
572    female
573    female
574    female
575      male
576      male
577    female
578    female
579    female
580    female
581    female
582    female
583    female
584    female
585    female
586    female
587    female
588    female
589    female
590      male
591      male
592      male
593    female
594    female
595    female
596      male
597      male
598    female
599    female
600    female
601    female
602    female
603      male
604      male
605      male
606    female
607    female
608    female
609    female
610      male
611    female
612      male
613    female
614    female
615    female
616    female
617      male
618      male
619      male
620    female
621      male
622      male
623      male
624    female
625      male
626      male
627      male
628      male
629    female
630      male
631      male
632    female
633    female
634      male
635      male
636    female
637    female
638      male
639    female
640      male
641    female
642    female
643    female
644      male
645    female
646    female
647    female
648    female
649    female
650      male
651    female
652    female
653    female
654    female
655    female
656      male
657      male
658    female
659      male
660      male
661      male
662    female
663    female
664      male
665    female
666    female
667    female
668      male
669      male
670    female
671      male
672    female
673    female
674    female
675    female
676    female
677    female
678      male
679      male
680    female
681      male
682      male
683    female
684      male
685    female
686      male
687      male
688      male
689      male
690    female
691    female
692    female
693    female
694    female
695    female
696    female
697    female
698    female
699      male
700    female
701    female
702      male
703    female
704    female
705      male
706      male
707      male
708      male
709    female
710      male
711    female
712    female
713      male
714    female
715    female
716      male
717    female
718    female
719      male
720    female
721      male
722    female
723      male
724      male
725      male
726    female
727      male
728    female
729      male
730    female
731      male
732    female
733      male
734    female
735      male
736      male
737    female
738      male
739      male
740      male
741    female
742    female
743    female
744      male
745      male
746      male
747      male
748    female
749      male
750      male
751      male
752      male
753    female
754      male
755    female
756      male
757      male
758    female
759      male
760    female
761    female
762      male
763    female
764      male
765    female
766    female
767      male
768    female
769      male
770      male
771      male
772    female
773    female
774      male
775    female
776    female
777    female
778    female
779      male
780    female
781    female
782    female
783    female
784      male
785    female
786    female
787    female
788      male
789    female
790    female
791    female
792      male
793      male
794    female
795    female
796      male
797    female
798      male
799    female
800      male
801      male
802    female
803    female
804    female
805      male
806    female
807    female
808      male
809      male
810      male
811      male
812    female
813      male
814    female
815      male
816    female
817      male
818    female
819    female
820    female
821    female
822      male
823    female
824    female
825      male
826    female
827    female
828    female
829      male
830    female
831    female
832      male
833    female
834      male
835    female
836      male
837    female
838      male
839    female
840    female
841      male
842    female
843      male
844    female
845      male
846      male
847      male
848    female
849      male
850      male
851    female
852    female
853      male
854      male
855    female
856      male
857    female
858      male
859      male
860    female
861    female
862      male
863    female
864      male
865      male
866      male
867      male
868      male
869      male
870      male
871    female
872      male
873      male
874    female
875      male
876      male
877      male
878    female
879    female
880      male
881    female
882    female
883      male
884    female
885    female
886    female
887      male
888    female
889      male
890    female
891    female
892    female
893      male
894    female
895    female
896      male
897    female
898      male
899    female
900      male
901    female
902    female
903    female
904    female
905      male
906      male
907    female
908    female
909      male
910      male
911    female
912    female
913    female
914    female
915    female
916      male
917    female
918    female
919      male
920      male
921    female
922      male
923    female
924      male
925      male
926      male
927    female
928      male
929    female
930      male
931      male
932      male
933      male
934      male
935      male
936      male
937    female
938      male
939      male
940      male
941    female
942      male
943      male
944    female
945    female
946      male
947    female
948      male
949    female
950      male
951    female
952    female
953      male
954    female
955      male
956      male
957    female
958    female
959      male
960    female
961    female
962    female
963    female
964      male
965    female
966      male
967      male
968    female
969    female
970    female
971      male
972    female
973    female
974    female
975    female
976      male
977      male
978      male
979    female
980    female
981      male
982      male
983    female
984    female
985      male
986    female
987      male
988    female
989    female
990      male
991    female
992    female
993    female
994      male
995    female
996      male
997    female
998    female
999    female
Name: gender, dtype: object

In [30]:
type(df['gender'])

pandas.core.series.Series

In [32]:
df['gender'].index

RangeIndex(start=0, stop=1000, step=1)

In [34]:
df['gender'].head(11)

0     female
1     female
2     female
3       male
4       male
5     female
6     female
7       male
8       male
9     female
10      male
Name: gender, dtype: object

In [35]:
df.gender

0      female
1      female
2      female
3        male
4        male
5      female
6      female
7        male
8        male
9      female
10       male
11       male
12     female
13       male
14     female
15     female
16       male
17     female
18       male
19     female
20       male
21     female
22       male
23     female
24       male
25       male
26       male
27     female
28       male
29     female
30     female
31     female
32     female
33       male
34       male
35       male
36     female
37     female
38     female
39       male
40       male
41     female
42     female
43       male
44     female
45       male
46     female
47     female
48     female
49       male
50       male
51       male
52       male
53       male
54     female
55     female
56     female
57       male
58       male
59     female
60       male
61       male
62       male
63     female
64     female
65       male
66       male
67     female
68       male
69     female
70     female
71       male
72     female
73       male
74       male
75       male
76       male
77       male
78     female
79     female
80     female
81       male
82       male
83       male
84       male
85     female
86     female
87     female
88     female
89     female
90     female
91       male
92       male
93       male
94     female
95       male
96       male
97     female
98     female
99     female
100      male
101      male
102    female
103      male
104      male
105    female
106    female
107      male
108    female
109    female
110    female
111      male
112      male
113    female
114    female
115      male
116    female
117    female
118    female
119    female
120    female
121      male
122    female
123      male
124      male
125    female
126      male
127      male
128      male
129    female
130      male
131      male
132      male
133    female
134      male
135      male
136      male
137      male
138    female
139      male
140    female
141    female
142    female
143      male
144      male
145    female
146      male
147      male
148    female
149      male
150      male
151      male
152    female
153      male
154      male
155    female
156    female
157      male
158    female
159      male
160      male
161    female
162      male
163      male
164    female
165    female
166      male
167    female
168    female
169    female
170      male
171      male
172    female
173    female
174    female
175    female
176    female
177    female
178    female
179    female
180      male
181    female
182    female
183    female
184      male
185      male
186      male
187      male
188      male
189    female
190    female
191      male
192    female
193      male
194    female
195      male
196      male
197      male
198    female
199    female
200    female
201    female
202      male
203    female
204      male
205      male
206      male
207      male
208    female
209    female
210      male
211      male
212    female
213      male
214      male
215      male
216    female
217    female
218      male
219      male
220    female
221      male
222    female
223      male
224    female
225    female
226    female
227      male
228      male
229    female
230      male
231      male
232    female
233      male
234      male
235      male
236      male
237    female
238      male
239      male
240      male
241    female
242    female
243      male
244      male
245      male
246      male
247    female
248    female
249      male
250      male
251    female
252    female
253      male
254      male
255    female
256    female
257      male
258    female
259    female
260    female
261      male
262    female
263    female
264      male
265      male
266    female
267    female
268    female
269    female
270      male
271      male
272    female
273    female
274      male
275      male
276    female
277    female
278    female
279      male
280      male
281      male
282    female
283    female
284    female
285      male
286      male
287    female
288      male
289      male
290      male
291      male
292      male
293    female
294      male
295      male
296      male
297      male
298      male
299      male
300      male
301      male
302    female
303      male
304    female
305      male
306      male
307      male
308    female
309    female
310    female
311      male
312      male
313    female
314    female
315      male
316    female
317      male
318      male
319    female
320    female
321    female
322    female
323    female
324    female
325    female
326      male
327      male
328      male
329    female
330      male
331      male
332      male
333      male
334    female
335    female
336      male
337      male
338    female
339    female
340      male
341    female
342    female
343      male
344      male
345    female
346      male
347    female
348      male
349      male
350    female
351      male
352    female
353    female
354    female
355    female
356      male
357    female
358      male
359    female
360    female
361      male
362    female
363    female
364      male
365      male
366      male
367      male
368    female
369    female
370      male
371    female
372      male
373    female
374    female
375      male
376    female
377    female
378    female
379      male
380    female
381      male
382      male
383    female
384    female
385    female
386    female
387    female
388    female
389      male
390      male
391    female
392      male
393      male
394    female
395      male
396    female
397    female
398      male
399      male
400    female
401      male
402    female
403    female
404    female
405    female
406      male
407    female
408    female
409      male
410    female
411      male
412      male
413      male
414    female
415      male
416      male
417      male
418      male
419      male
420    female
421    female
422    female
423    female
424      male
425    female
426      male
427      male
428      male
429      male
430      male
431    female
432      male
433    female
434      male
435      male
436      male
437      male
438      male
439      male
440    female
441    female
442    female
443    female
444      male
445    female
446      male
447      male
448      male
449      male
450    female
451    female
452    female
453      male
454    female
455      male
456    female
457      male
458    female
459      male
460      male
461      male
462    female
463    female
464      male
465    female
466    female
467      male
468    female
469      male
470    female
471    female
472    female
473    female
474    female
475    female
476      male
477      male
478    female
479      male
480      male
481    female
482      male
483      male
484    female
485      male
486      male
487    female
488      male
489      male
490    female
491    female
492    female
493    female
494    female
495      male
496    female
497    female
498    female
499      male
500    female
501    female
502      male
503    female
504    female
505    female
506      male
507      male
508      male
509    female
510      male
511      male
512      male
513    female
514    female
515    female
516    female
517    female
518    female
519    female
520      male
521    female
522      male
523      male
524      male
525      male
526      male
527    female
528    female
529    female
530    female
531    female
532      male
533    female
534      male
535    female
536      male
537    female
538      male
539      male
540      male
541      male
542    female
543    female
544    female
545      male
546    female
547      male
548    female
549      male
550      male
551      male
552    female
553      male
554      male
555    female
556    female
557      male
558    female
559      male
560    female
561    female
562      male
563    female
564      male
565      male
566    female
567    female
568      male
569      male
570      male
571      male
572    female
573    female
574    female
575      male
576      male
577    female
578    female
579    female
580    female
581    female
582    female
583    female
584    female
585    female
586    female
587    female
588    female
589    female
590      male
591      male
592      male
593    female
594    female
595    female
596      male
597      male
598    female
599    female
600    female
601    female
602    female
603      male
604      male
605      male
606    female
607    female
608    female
609    female
610      male
611    female
612      male
613    female
614    female
615    female
616    female
617      male
618      male
619      male
620    female
621      male
622      male
623      male
624    female
625      male
626      male
627      male
628      male
629    female
630      male
631      male
632    female
633    female
634      male
635      male
636    female
637    female
638      male
639    female
640      male
641    female
642    female
643    female
644      male
645    female
646    female
647    female
648    female
649    female
650      male
651    female
652    female
653    female
654    female
655    female
656      male
657      male
658    female
659      male
660      male
661      male
662    female
663    female
664      male
665    female
666    female
667    female
668      male
669      male
670    female
671      male
672    female
673    female
674    female
675    female
676    female
677    female
678      male
679      male
680    female
681      male
682      male
683    female
684      male
685    female
686      male
687      male
688      male
689      male
690    female
691    female
692    female
693    female
694    female
695    female
696    female
697    female
698    female
699      male
700    female
701    female
702      male
703    female
704    female
705      male
706      male
707      male
708      male
709    female
710      male
711    female
712    female
713      male
714    female
715    female
716      male
717    female
718    female
719      male
720    female
721      male
722    female
723      male
724      male
725      male
726    female
727      male
728    female
729      male
730    female
731      male
732    female
733      male
734    female
735      male
736      male
737    female
738      male
739      male
740      male
741    female
742    female
743    female
744      male
745      male
746      male
747      male
748    female
749      male
750      male
751      male
752      male
753    female
754      male
755    female
756      male
757      male
758    female
759      male
760    female
761    female
762      male
763    female
764      male
765    female
766    female
767      male
768    female
769      male
770      male
771      male
772    female
773    female
774      male
775    female
776    female
777    female
778    female
779      male
780    female
781    female
782    female
783    female
784      male
785    female
786    female
787    female
788      male
789    female
790    female
791    female
792      male
793      male
794    female
795    female
796      male
797    female
798      male
799    female
800      male
801      male
802    female
803    female
804    female
805      male
806    female
807    female
808      male
809      male
810      male
811      male
812    female
813      male
814    female
815      male
816    female
817      male
818    female
819    female
820    female
821    female
822      male
823    female
824    female
825      male
826    female
827    female
828    female
829      male
830    female
831    female
832      male
833    female
834      male
835    female
836      male
837    female
838      male
839    female
840    female
841      male
842    female
843      male
844    female
845      male
846      male
847      male
848    female
849      male
850      male
851    female
852    female
853      male
854      male
855    female
856      male
857    female
858      male
859      male
860    female
861    female
862      male
863    female
864      male
865      male
866      male
867      male
868      male
869      male
870      male
871    female
872      male
873      male
874    female
875      male
876      male
877      male
878    female
879    female
880      male
881    female
882    female
883      male
884    female
885    female
886    female
887      male
888    female
889      male
890    female
891    female
892    female
893      male
894    female
895    female
896      male
897    female
898      male
899    female
900      male
901    female
902    female
903    female
904    female
905      male
906      male
907    female
908    female
909      male
910      male
911    female
912    female
913    female
914    female
915    female
916      male
917    female
918    female
919      male
920      male
921    female
922      male
923    female
924      male
925      male
926      male
927    female
928      male
929    female
930      male
931      male
932      male
933      male
934      male
935      male
936      male
937    female
938      male
939      male
940      male
941    female
942      male
943      male
944    female
945    female
946      male
947    female
948      male
949    female
950      male
951    female
952    female
953      male
954    female
955      male
956      male
957    female
958    female
959      male
960    female
961    female
962    female
963    female
964      male
965    female
966      male
967      male
968    female
969    female
970    female
971      male
972    female
973    female
974    female
975    female
976      male
977      male
978      male
979    female
980    female
981      male
982      male
983    female
984    female
985      male
986    female
987      male
988    female
989    female
990      male
991    female
992    female
993    female
994      male
995    female
996      male
997    female
998    female
999    female
Name: gender, dtype: object

In [37]:
#selecting teo or more column
#using[[]]
df[['gender','math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
5    female          71
6    female          88
7      male          40
8      male          64
9    female          38
10     male          58
11     male          40
12   female          65
13     male          78
14   female          50
15   female          69
16     male          88
17   female          18
18     male          46
19   female          54
20     male          66
21   female          65
22     male          44
23   female          69
24     male          74
25     male          73
26     male          69
27   female          67
28     male          70
29   female          62
30   female          69
31   female          63
32   female          56
33     male          40
34     male          97
35     male          81
36   female          74
37   female          50
38   female          75
39     male          57
40     male          55
41   female          58
42   female          53
43     male          59
44   female          50
45     male          65
46   female          55
47   female          66
48   female          57
49     male          82
50     male          53
51     male          77
52     male          53
53     male          88
54   female          71
55   female          33
56   female          82
57     male          52
58     male          58
59   female           0
60     male          79
61     male          39
62     male          62
63   female          69
64   female          59
65     male          67
66     male          45
67   female          60
68     male          61
69   female          39
70   female          58
71     male          63
72   female          41
73     male          61
74     male          49
75     male          44
76     male          30
77     male          80
78   female          61
79   female          62
80   female          47
81     male          49
82     male          50
83     male          72
84     male          42
85   female          73
86   female          76
87   female          71
88   female          58
89   female          73
90   female          65
91     male          27
92     male          71
93     male          43
94   female          79
95     male          78
96     male          65
97   female          63
98   female          58
99   female          65
100    male          79
101    male          68
102  female          85
103    male          60
104    male          98
105  female          58
106  female          87
107    male          66
108  female          52
109  female          70
110  female          77
111    male          62
112    male          54
113  female          51
114  female          99
115    male          84
116  female          75
117  female          78
118  female          51
119  female          55
120  female          79
121    male          91
122  female          88
123    male          63
124    male          83
125  female          87
126    male          72
127    male          65
128    male          82
129  female          51
130    male          89
131    male          53
132    male          87
133  female          75
134    male          74
135    male          58
136    male          51
137    male          70
138  female          59
139    male          71
140  female          76
141  female          59
142  female          42
143    male          57
144    male          88
145  female          22
146    male          88
147    male          73
148  female          68
149    male         100
150    male          62
151    male          77
152  female          59
153    male          54
154    male          62
155  female          70
156  female          66
157    male          60
158  female          61
159    male          66
160    male          82
161  female          75
162    male          49
163    male          52
164  female          81
165  female          96
166    male          53
167  female          58
168  female          68
169  female          67
170    male          72
171    male          94
172  female          79
173  female          63
174  female          43
175  female          81
176  female          46
177  female          71
178  female          52
179  female          97
180    male          62
181  female          46
182  female          50
183  female          65
184    male          45
185    male          65
186    male          80
187    male          62
188    male          48
189  female          77
190  female          66
191    male          76
192  female          62
193    male          77
194  female          69
195    male          61
196    male          59
197    male          55
198  female          45
199  female          78
200  female          67
201  female          65
202    male          69
203  female          57
204    male          59
205    male          74
206    male          82
207    male          81
208  female          74
209  female          58
210    male          80
211    male          35
212  female          42
213    male          60
214    male          87
215    male          84
216  female          83
217  female          34
218    male          66
219    male          61
220  female          56
221    male          87
222  female          55
223    male          86
224  female          52
225  female          45
226  female          72
227    male          57
228    male          68
229  female          88
230    male          76
231    male          46
232  female          67
233    male          92
234    male          83
235    male          80
236    male          63
237  female          64
238    male          54
239    male          84
240    male          73
241  female          80
242  female          56
243    male          59
244    male          75
245    male          85
246    male          89
247  female          58
248  female          65
249    male          68
250    male          47
251  female          71
252  female          60
253    male          80
254    male          54
255  female          62
256  female          64
257    male          78
258  female          70
259  female          65
260  female          64
261    male          79
262  female          44
263  female          99
264    male          76
265    male          59
266  female          63
267  female          69
268  female          88
269  female          71
270    male          69
271    male          58
272  female          47
273  female          65
274    male          88
275    male          83
276  female          85
277  female          59
278  female          65
279    male          73
280    male          53
281    male          45
282  female          73
283  female          70
284  female          37
285    male          81
286    male          97
287  female          67
288    male          88
289    male          77
290    male          76
291    male          86
292    male          63
293  female          65
294    male          78
295    male          67
296    male          46
297    male          71
298    male          40
299    male          90
300    male          81
301    male          56
302  female          67
303    male          80
304  female          74
305    male          69
306    male          99
307    male          51
308  female          53
309  female          49
310  female          73
311    male          66
312    male          67
313  female          68
314  female          59
315    male          71
316  female          77
317    male          83
318    male          63
319  female          56
320  female          67
321  female          75
322  female          71
323  female          43
324  female          41
325  female          82
326    male          61
327    male          28
328    male          82
329  female          41
330    male          71
331    male          47
332    male          62
333    male          90
334  female          83
335  female          61
336    male          76
337    male          49
338  female          24
339  female          35
340    male          58
341  female          61
342  female          69
343    male          67
344    male          79
345  female          72
346    male          62
347  female          77
348    male          75
349    male          87
350  female          52
351    male          66
352  female          63
353  female          46
354  female          59
355  female          61
356    male          63
357  female          42
358    male          59
359  female          80
360  female          58
361    male          85
362  female          52
363  female          27
364    male          59
365    male          49
366    male          69
367    male          61
368  female          44
369  female          73
370    male          84
371  female          45
372    male          74
373  female          82
374  female          59
375    male          46
376  female          80
377  female          85
378  female          71
379    male          66
380  female          80
381    male          87
382    male          79
383  female          38
384  female          38
385  female          67
386  female          64
387  female          57
388  female          62
389    male          73
390    male          73
391  female          77
392    male          76
393    male          57
394  female          65
395    male          48
396  female          50
397  female          85
398    male          74
399    male          60
400  female          59
401    male          53
402  female          49
403  female          88
404  female          54
405  female          63
406    male          65
407  female          82
408  female          52
409    male          87
410  female          70
411    male          84
412    male          71
413    male          63
414  female          51
415    male          84
416    male          71
417    male          74
418    male          68
419    male          57
420  female          82
421  female          57
422  female          47
423  female          59
424    male          41
425  female          62
426    male          86
427    male          69
428    male          65
429    male          68
430    male          64
431  female          61
432    male          61
433  female          47
434    male          73
435    male          50
436    male          75
437    male          75
438    male          70
439    male          89
440  female          67
441  female          78
442  female          59
443  female          73
444    male          79
445  female          67
446    male          69
447    male          86
448    male          47
449    male          81
450  female          64
451  female         100
452  female          65
453    male          65
454  female          53
455    male          37
456  female          79
457    male          53
458  female         100
459    male          72
460    male          53
461    male          54
462  female          71
463  female          77
464    male          75
465  female          84
466  female          26
467    male          72
468  female          77
469    male          91
470  female          83
471  female          63
472  female          68
473  female          59
474  female          90
475  female          71
476    male          76
477    male          80
478  female          55
479    male          76
480    male          73
481  female          52
482    male          68
483    male          59
484  female          49
485    male          70
486    male          61
487  female          60
488    male          64
489    male          79
490  female          65
491  female          64
492  female          83
493  female          81
494  female          54
495    male          68
496  female          54
497  female          59
498  female          66
499    male          76
500  female          74
501  female          94
502    male          63
503  female          95
504  female          40
505  female          82
506    male          68
507    male          55
508    male          79
509  female          86
510    male          76
511    male          64
512    male          62
513  female          54
514  female          77
515  female          76
516  female          74
517  female          66
518  female          66
519  female          67
520    male          71
521  female          91
522    male          69
523    male          54
524    male          53
525    male          68
526    male          56
527  female          36
528  female          29
529  female          62
530  female          68
531  female          47
532    male          62
533  female          79
534    male          73
535  female          66
536    male          51
537  female          51
538    male          85
539    male          97
540    male          75
541    male          79
542  female          81
543  female          82
544  female          64
545    male          78
546  female          92
547    male          72
548  female          62
549    male          79
550    male          79
551    male          87
552  female          40
553    male          77
554    male          53
555  female          32
556  female          55
557    male          61
558  female          53
559    male          73
560  female          74
561  female          63
562    male          96
563  female          63
564    male          48
565    male          48
566  female          92
567  female          61
568    male          63
569    male          68
570    male          71
571    male          91
572  female          53
573  female          50
574  female          74
575    male          40
576    male          61
577  female          81
578  female          48
579  female          53
580  female          81
581  female          77
582  female          63
583  female          73
584  female          69
585  female          65
586  female          55
587  female          44
588  female          54
589  female          48
590    male          58
591    male          71
592    male          68
593  female          74
594  female          92
595  female          56
596    male          30
597    male          53
598  female          69
599  female          65
600  female          54
601  female          29
602  female          76
603    male          60
604    male          84
605    male          75
606  female          85
607  female          40
608  female          61
609  female          58
610    male          69
611  female          58
612    male          94
613  female          65
614  female          82
615  female          60
616  female          37
617    male          88
618    male          95
619    male          65
620  female          35
621    male          62
622    male          58
623    male         100
624  female          61
625    male         100
626    male          69
627    male          61
628    male          49
629  female          44
630    male          67
631    male          79
632  female          66
633  female          75
634    male          84
635    male          71
636  female          67
637  female          80
638    male          86
639  female          76
640    male          41
641  female          74
642  female          72
643  female          74
644    male          70
645  female          65
646  female          59
647  female          64
648  female          50
649  female          69
650    male          51
651  female          68
652  female          85
653  female          65
654  female          73
655  female          62
656    male          77
657    male          69
658  female          43
659    male          90
660    male          74
661    male          73
662  female          55
663  female          65
664    male          80
665  female          50
666  female          63
667  female          77
668    male          73
669    male          81
670  female          66
671    male          52
672  female          69
673  female          65
674  female          69
675  female          50
676  female          73
677  female          70
678    male          81
679    male          63
680  female          67
681    male          60
682    male          62
683  female          29
684    male          62
685  female          94
686    male          85
687    male          77
688    male          53
689    male          93
690  female          49
691  female          73
692  female          66
693  female          77
694  female          49
695  female          79
696  female          75
697  female          59
698  female          57
699    male          66
700  female          79
701  female          57
702    male          87
703  female          63
704  female          59
705    male          62
706    male          46
707    male          66
708    male          89
709  female          42
710    male          93
711  female          80
712  female          98
713    male          81
714  female          60
715  female          76
716    male          73
717  female          96
718  female          76
719    male          91
720  female          62
721    male          55
722  female          74
723    male          50
724    male          47
725    male          81
726  female          65
727    male          68
728  female          73
729    male          53
730  female          68
731    male          55
732  female          87
733    male          55
734  female          53
735    male          67
736    male          92
737  female          53
738    male          81
739    male          61
740    male          80
741  female          37
742  female          81
743  female          59
744    male          55
745    male          72
746    male          69
747    male          69
748  female          50
749    male          87
750    male          71
751    male          68
752    male          79
753  female          77
754    male          58
755  female          84
756    male          55
757    male          70
758  female          52
759    male          69
760  female          53
761  female          48
762    male          78
763  female          62
764    male          60
765  female          74
766  female          58
767    male          76
768  female          68
769    male          58
770    male          52
771    male          75
772  female          52
773  female          62
774    male          66
775  female          49
776  female          66
777  female          35
778  female          72
779    male          94
780  female          46
781  female          77
782  female          76
783  female          52
784    male          91
785  female          32
786  female          72
787  female          19
788    male          68
789  female          52
790  female          48
791  female          60
792    male          66
793    male          89
794  female          42
795  female          57
796    male          70
797  female          70
798    male          69
799  female          52
800    male          67
801    male          76
802  female          87
803  female          82
804  female          73
805    male          75
806  female          64
807  female          41
808    male          90
809    male          59
810    male          51
811    male          45
812  female          54
813    male          87
814  female          72
815    male          94
816  female          45
817    male          61
818  female          60
819  female          77
820  female          85
821  female          78
822    male          49
823  female          71
824  female          48
825    male          62
826  female          56
827  female          65
828  female          69
829    male          68
830  female          61
831  female          74

In [38]:
type([['gender','math score']])

list

In [40]:
#selecting multiple columns
df[['gender','math score','reading score','writing score','race/ethnicity']]

     gender  math score  reading score  writing score race/ethnicity
0    female          72             72             74        group B
1    female          69             90             88        group C
2    female          90             95             93        group B
3      male          47             57             44        group A
4      male          76             78             75        group C
5    female          71             83             78        group B
6    female          88             95             92        group B
7      male          40             43             39        group B
8      male          64             64             67        group D
9    female          38             60             50        group B
10     male          58             54             52        group C
11     male          40             52             43        group D
12   female          65             81             73        group B
13     male          78             72             70        group A
14   female          50             53             58        group A
15   female          69             75             78        group C
16     male          88             89             86        group C
17   female          18             32             28        group B
18     male          46             42             46        group C
19   female          54             58             61        group C
20     male          66             69             63        group D
21   female          65             75             70        group B
22     male          44             54             53        group D
23   female          69             73             73        group C
24     male          74             71             80        group D
25     male          73             74             72        group A
26     male          69             54             55        group B
27   female          67             69             75        group C
28     male          70             70             65        group C
29   female          62             70             75        group D
30   female          69             74             74        group D
31   female          63             65             61        group B
32   female          56             72             65        group E
33     male          40             42             38        group D
34     male          97             87             82        group E
35     male          81             81             79        group E
36   female          74             81             83        group D
37   female          50             64             59        group D
38   female          75             90             88        group D
39     male          57             56             57        group B
40     male          55             61             54        group C
41   female          58             73             68        group C
42   female          53             58             65        group B
43     male          59             65             66        group B
44   female          50             56             54        group E
45     male          65             54             57        group B
46   female          55             65             62        group A
47   female          66             71             76        group C
48   female          57             74             76        group D
49     male          82             84             82        group C
50     male          53             55             48        group E
51     male          77             69             68        group E
52     male          53             44             42        group C
53     male          88             78             75        group D
54   female          71             84             87        group C
55   female          33             41             43        group C
56   female          82             85             86        group E
57     male          52             55             49        group D
58     male          58             59             58        group D
59   female           0             17             10        group C
60     male          79             74             72        group E
61     male          39             39             34        group A
62     male          62             61             55        group A
63   female          69             80             71        group C
64   female          59             58             59        group D
65     male          67             64             61        group B
66     male          45             37             37        group D
67   female          60             72             74        group C
68     male          61             58             56        group B
69   female          39             64             57        group C
70   female          58             63             73        group D
71     male          63             55             63        group D
72   female          41             51             48        group A
73     male          61             57             56        group C
74     male          49             49             41        group C
75     male          44             41             38        group B
76     male          30             26             22        group E
77     male          80             78             81        group A
78   female          61             74             72        group D
79   female          62             68             68        group E
80   female          47             49             50        group B
81     male          49             45             45        group B
82     male          50             47             54        group A
83     male          72             64             63        group E
84     male          42             39             34        group D
85   female          73             80             82        group C
86   female          76             83             88        group C
87   female          71             71             74        group D
88   female          58             70             67        group A
89   female          73             86             82        group D
90   female          65             72             74        group C
91     male          27             34             36        group C
92     male          71             79             71        group C
93     male          43             45             50        group C
94   female          79             86             92        group B
95     male          78             81             82        group C
96     male          65             66             62        group B
97   female          63             72             70        group E
98   female          58             67             62        group D
99   female          65             67             62        group D
100    male          79             67             67        group B
101    male          68             74             74        group D
102  female          85             91             89        group D
103    male          60             44             47        group B
104    male          98             86             90        group C
105  female          58             67             72        group C
106  female          87            100            100        group D
107    male          66             63             64        group E
108  female          52             76             70        group B
109  female          70             64             72        group B
110  female          77             89             98        group D
111    male          62             55             49        group C
112    male          54             53             47        group A
113  female          51             58             54        group D
114  female          99            100            100        group E
115    male          84             77             74        group C
116  female          75             85             82        group B
117  female          78             82             79        group D
118  female          51             63             61        group D
119  female          55             69             65        group C
120  female          79             92             89        group C
121    male          91             89             92        group B
122  female          88             93             93        group C
123    male          63             57             56        group D
124    male          83             80             73        group E
125  female          87             95             86        group B
126    male          72             68             67        group B
127    male          65             77             74        group D
128    male          82             82             74        group D
129  female          51             49             51        group A
130    male          89             84             82        group D
131    male          53             37             40        group C
132    male          87             74             70        group E
133  female          75             81             84        group C
134    male          74             79             75        group D
135    male          58             55             48        group C
136    male          51             54             41        group B
137    male          70             55             56        group E
138  female          59             66             67        group C
139    male          71             61             69        group D
140  female          76             72             71        group D
141  female          59             62             64        group C
142  female          42             55             54        group E
143    male          57             43             47        group A
144    male          88             73             78        group D
145  female          22             39             33        group C
146    male          88             84             75        group B
147    male          73             68             66        group C
148  female          68             75             81        group D
149    male         100            100             93        group E
150    male          62             67             69        group A
151    male          77             67             68        group A
152  female          59             70             66        group B
153    male          54             49             47        group D
154    male          62             67             61        group D
155  female          70             89             88        group C
156  female          66             74             78        group E
157    male          60             60             60        group B
158  female          61             86             87        group B
159    male          66             62             64        group D
160    male          82             78             74        group B
161  female          75             88             85        group E
162    male          49             53             52        group B
163    male          52             53             49        group C
164  female          81             92             91        group E
165  female          96            100            100        group C
166    male          53             51             51        group C
167  female          58             76             78        group B
168  female          68             83             78        group B
169  female          67             75             70        group C
170    male          72             73             74        group A
171    male          94             88             78        group E
172  female          79             86             81        group D
173  female          63             67             70        group C
174  female          43             51             54        group C
175  female          81             91             87        group C
176  female          46             54             58        group B
177  female          71             77             77        group C
178  female          52             70             62        group B
179  female          97            100            100        group D
180    male          62             68             75        group C
181  female          46             64             66        group C
182  female          50             50             47        group E
183  female          65             69             70        group D
184    male          45             52             49        group C
185    male          65             67             65        group C
186    male          80             76             65        group E
187    male          62             66             68        group D
188    male          48             52             45        group B
189  female          77             88             87        group C
190  female          66             65             69        group E
191    male          76             83             79        group D
192  female          62             64             66        group B
193    male          77             62             62        group D
194  female          69             84             85        group C
195    male          61             55             52        group D
196    male          59             69             65        group C
197    male          55             56             51        group E
198  female          45             53             55        group B
199  female          78             79             76        group B
200  female          67             84             86        group C
201  female          65             81             77        group D
202    male          69             77             69        group C
203  female          57             69             68        group B
204    male          59             41             42        group C
205    male          74             71             78        group D
206    male          82             62             62        group E
207    male          81             80             76        group E
208  female          74             81             76        group B
209  female          58             61             66        group B
210    male          80             79             79        group D
211    male          35             28             27        group C
212  female          42             62             60        group C
213    male          60             51             56        group C
214    male          87             91             81        group E
215    male          84             83             75        group B
216  female          83             86             88        group E
217  female          34             42             39        group C
218    male          66             77             70        group B
219    male          61             56             56        group B
220  female          56             68             74        group D
221    male          87             85             73        group B
222  female          55             65             62        group C
223    male          86             80             75        group D
224  female          52             66             73        group B
225  female          45             56             54        group E
226  female          72             72             71        group C
227    male          57             50             54        group D
228    male          68             72             64        group A
229  female          88             95             94        group C
230    male          76             64             66        group D
231    male          46             43             42        group C
232  female          67             86             83        group B
233    male          92             87             78        group E
234    male          83             82             84        group C
235    male          80             75             77        group D
236    male          63             66             67        group D
237  female          64             60             74        group D
238    male          54             52             51        group B
239    male          84             80             80        group C
240    male          73             68             66        group D
241  female          80             83             83        group E
242  female          56             52             55        group D
243    male          59             51             43        group E
244    male          75             74             69        group D
245    male          85             76             71        group C
246    male          89             76             74        group E
247  female          58             70             68        group B
248  female          65             64             62        group B
249    male          68             60             53        group C
250    male          47             49             49        group A
251  female          71             83             83        group D
252  female          60             70             70        group B
253    male          80             80             72        group D
254    male          54             52             52        group D
255  female          62             73             70        group E
256  female          64             73             68        group C
257    male          78             77             77        group C
258  female          70             75             78        group B
259  female          65             81             81        group C
260  female          64             79             77        group C
261    male          79             79             78        group C
262  female          44             50             51        group C
263  female          99             93             90        group E
264    male          76             73             68        group D
265    male          59             42             41        group D
266  female          63             75             81        group C
267  female          69             72             77        group D
268  female          88             92             95        group D
269  female          71             76             70        group E
270    male          69             63             61        group C
271    male          58             49             42        group C
272  female          47             53             58        group D
273  female          65             70             71        group D
274    male          88             85             76        group B
275    male          83             78             73        group C
276  female          85             92             93        group C
277  female          59             63             75        group E
278  female          65             86             80        group C
279    male          73             56             57        group B
280    male          53             52             42        group D
281    male          45             48             46        group D
282  female          73             79             84        group D
283  female          70             78             78        group D
284  female          37             46             46        group B
285    male          81             82             82        group B
286    male          97             82             88        group E
287  female          67             89             82        group B

In [41]:
#adding new column in a table
df['language score']=90

In [42]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,90
1,female,group C,some college,standard,completed,69,90,88,90
2,female,group B,master's degree,standard,none,90,95,93,90
3,male,group A,associate's degree,free/reduced,none,47,57,44,90
4,male,group C,some college,standard,none,76,78,75,90
5,female,group B,associate's degree,standard,none,71,83,78,90
6,female,group B,some college,standard,completed,88,95,92,90
7,male,group B,some college,free/reduced,none,40,43,39,90
8,male,group D,high school,free/reduced,completed,64,64,67,90
9,female,group B,high school,free/reduced,none,38,60,50,90
10,male,group C,associate's degree,standard,none,58,54,52,90
11,male,group D,associate's degree,standard,none,40,52,43,90
12,female,group B,high school,standard,none,65,81,73,90
13,male,group A,some college,standard,completed,78,72,70,90
14,female,group A,master's degree,standard,none,50,53,58,90
15,female,group C,some high school,standard,none,69,75,78,90
16,male,group C,high school,standard,none,88,89,86,90
17,female,group B,some high school,free/reduced,none,18,32,28,90
18,male,group C,master's degree,free/reduced,completed,46,42,46,90
19,female,group C,associate's degree,free/reduced,none,54,58,61,90
20,male,group D,high school,standard,none,66,69,63,90
21,female,group B,some college,free/reduced,completed,65,75,70,90
22,male,group D,some college,standard,none,44,54,53,90
23,female,group C,some high school,standard,none,69,73,73,90
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,90
25,male,group A,master's degree,free/reduced,none,73,74,72,90
26,male,group B,some college,standard,none,69,54,55,90
27,female,group C,bachelor's degree,standard,none,67,69,75,90
28,male,group C,high school,standard,none,70,70,65,90
29,female,group D,master's degree,standard,none,62,70,75,90
30,female,group D,some college,standard,none,69,74,74,90
31,female,group B,some college,standard,none,63,65,61,90
32,female,group E,master's degree,free/reduced,none,56,72,65,90
33,male,group D,some college,standard,none,40,42,38,90
34,male,group E,some college,standard,none,97,87,82,90
35,male,group E,associate's degree,standard,completed,81,81,79,90
36,female,group D,associate's degree,standard,none,74,81,83,90
37,female,group D,some high school,free/reduced,none,50,64,59,90
38,female,group D,associate's degree,free/reduced,completed,75,90,88,90
39,male,group B,associate's degree,free/reduced,none,57,56,57,90
40,male,group C,associate's degree,free/reduced,none,55,61,54,90
41,female,group C,associate's degree,standard,none,58,73,68,90
42,female,group B,associate's degree,standard,none,53,58,65,90
43,male,group B,some college,free/reduced,completed,59,65,66,90
44,female,group E,associate's degree,free/reduced,none,50,56,54,90
45,male,group B,associate's degree,standard,none,65,54,57,90
46,female,group A,associate's degree,standard,completed,55,65,62,90
47,female,group C,high school,standard,none,66,71,76,90
48,female,group D,associate's degree,free/reduced,completed,57,74,76,90
49,male,group C,high school,standard,completed,82,84,82,90
50,male,group E,some college,standard,none,53,55,48,90
51,male,group E,associate's degree,free/reduced,completed,77,69,68,90
52,male,group C,some college,standard,none,53,44,42,90
53,male,group D,high school,standard,none,88,78,75,90
54,female,group C,some high school,free/reduced,completed,71,84,87,90
55,female,group C,high school,free/reduced,none,33,41,43,90
56,female,group E,associate's degree,standard,completed,82,85,86,90
57,male,group D,associate's degree,standard,none,52,55,49,90
58,male,group D,some college,standard,completed,58,59,58,90
59,female,group C,some high school,free/reduced,none,0,17,10,90
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,90
61,male,group A,some high school,free/reduced,none,39,39,34,90
62,male,group A,associate's degree,free/reduced,none,62,61,55,90
63,female,group C,associate's degree,standard,none,69,80,71,90
64,female,group D,some high school,standard,none,59,58,59,90
65,male,group B,some high school,standard,none,67,64,61,90
66,male,group D,some high school,free/reduced,none,45,37,37,90
67,female,group C,some college,standard,none,60,72,74,90
68,male,group B,associate's degree,free/reduced,none,61,58,56,90
69,female,group C,associate's degree,standard,none,39,64,57,90
70,female,group D,some college,free/reduced,completed,58,63,73,90
71,male,group D,some college,standard,completed,63,55,63,90
72,female,group A,associate's degree,free/reduced,none,41,51,48,90
73,male,group C,some high school,free/reduced,none,61,57,56,90
74,male,group C,some high school,standard,none,49,49,41,90
75,male,group B,associate's degree,free/reduced,none,44,41,38,90
76,male,group E,some high school,standard,none,30,26,22,90
77,male,group A,bachelor's degree,standard,completed,80,78,81,90
78,female,group D,some high school,standard,completed,61,74,72,90
79,female,group E,master's degree,standard,none,62,68,68,90
80,female,group B,associate's degree,standard,none,47,49,50,90
81,male,group B,high school,free/reduced,none,49,45,45,90
82,male,group A,some college,free/reduced,completed,50,47,54,90
83,male,group E,associate's degree,standard,none,72,64,63,90
84,male,group D,high school,free/reduced,none,42,39,34,90
85,female,group C,some college,standard,none,73,80,82,90
86,female,group C,some college,free/reduced,none,76,83,88,90
87,female,group D,associate's degree,standard,none,71,71,74,90
88,female,group A,some college,standard,none,58,70,67,90
89,female,group D,some high school,standard,none,73,86,82,90
90,female,group C,bachelor's degree,standard,none,65,72,74,90
91,male,group C,high school,free/reduced,none,27,34,36,90
92,male,group C,high school,standard,none,71,79,71,90
93,male,group C,associate's degree,free/reduced,completed,43,45,50,90
94,female,group B,some college,standard,none,79,86,92,90
95,male,group C,associate's degree,free/reduced,completed,78,81,82,90
96,male,group B,some high school,standard,completed,65,66,62,90
97,female,group E,some college,standard,completed,63,72,70,90
98,female,group D,some college,free/reduced,none,58,67,62,90
99,female,group D,bachelor's degree,standard,none,65,67,62,90
100,male,group B,some college,standard,none,79,67,67,90
101,male,group D,bachelor's degree,standard,completed,68,74,74,90
102,female,group D,associate's degree,standard,none,85,91,89,90
103,male,group B,high school,standard,completed,60,44,47,90
104,male,group C,some college,standard,completed,98,86,90,90
105,female,group C,some college,standard,none,58,67,72,90
106,female,group D,master's degree,standard,none,87,100,100,90
107,male,group E,associate's degree,standard,completed,66,63,64,90
108,female,group B,associate's degree,free/reduced,none,52,76,70,90
109,female,group B,some high school,standard,none,70,64,72,90
110,female,group D,associate's degree,free/reduced,completed,77,89,98,90
111,male,group C,high school,standard,none,62,55,49,90
112,male,group A,associate's degree,standard,none,54,53,47,90
113,female,group D,some college,standard,none,51,58,54,90
114,female,group E,bachelor's degree,standard,completed,99,100,100,90
115,male,group C,high school,standard,none,84,77,74,90
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,90
117,female,group D,bachelor's degree,standard,none,78,82,79,90
118,female,group D,some high school,standard,none,51,63,61,90
119,female,group C,some college,standard,none,55,69,65,90
120,female,group C,bachelor's degree,standard,completed,79,92,89,90
121,male,group B,associate's degree,standard,completed,91,89,92,90
122,female,group C,some college,standard,completed,88,93,93,90
123,male,group D,high school,free/reduced,none,63,57,56,90
124,male,group E,some college,standard,none,83,80,73,90
125,female,group B,high school,standard,none,87,95,86,90
126,male,group B,some high school,standard,none,72,68,67,90
127,male,group D,some college,standard,completed,65,77,74,90
128,male,group D,master's degree,standard,none,82,82,74,90
129,female,group A,bachelor's degree,standard,none,51,49,51,90
130,male,group D,master's degree,standard,none,89,84,82,90
131,male,group C,some high school,free/reduced,completed,53,37,40,90
132,male,group E,some college,free/reduced,completed,87,74,70,90
133,female,group C,some college,standard,completed,75,81,84,90
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,90
135,male,group C,bachelor's degree,standard,none,58,55,48,90
136,male,group B,some high school,standard,completed,51,54,41,90
137,male,group E,high school,standard,none,70,55,56,90
138,female,group C,associate's degree,standard,none,59,66,67,90
139,male,group D,some college,standard,completed,71,61,69,90
140,female,group D,some high school,standard,none,76,72,71,90
141,female,group C,some college,free/reduced,none,59,62,64,90
142,female,group E,some college,free/reduced,completed,42,55,54,90
143,male,group A,high school,standard,none,57,43,47,90
144,male,group D,some college,standard,none,88,73,78,90
145,female,group C,some college,free/reduced,none,22,39,33,90
146,male,group B,some high school,standard,none,88,84,75,90
147,male,group C,associate's degree,free/reduced,none,73,68,66,90
148,female,group D,bachelor's degree,standard,completed,68,75,81,90
149,male,group E,associate's degree,free/reduced,completed,100,100,93,90
150,male,group A,some high school,standard,completed,62,67,69,90
151,male,group A,bachelor's degree,standard,none,77,67,68,90
152,female,group B,associate's degree,standard,completed,59,70,66,90
153,male,group D,bachelor's degree,standard,none,54,49,47,90
154,male,group D,some high school,standard,none,62,67,61,90
155,female,group C,some college,standard,completed,70,89,88,90
156,female,group E,high school,free/reduced,completed,66,74,78,90
157,male,group B,some college,free/reduced,none,60,60,60,90
158,female,group B,associate's degree,standard,completed,61,86,87,90
159,male,group D,associate's degree,free/reduced,none,66,62,64,90
160,male,group B,associate's degree,free/reduced,completed,82,78,74,90
161,female,group E,some college,free/reduced,completed,75,88,85,90
162,male,group B,master's degree,free/reduced,none,49,53,52,90
163,male,group C,high school,standard,none,52,53,49,90
164,female,group E,master's degree,standard,none,81,92,91,90
165,female,group C,bachelor's degree,standard,completed,96,100,100,90
166,male,group C,high school,free/reduced,completed,53,51,51,90
167,female,group B,master's degree,free/reduced,completed,58,76,78,90
168,female,group B,high school,standard,completed,68,83,78,90
169,female,group C,some college,free/reduced,completed,67,75,70,90
170,male,group A,high school,standard,completed,72,73,74,90
171,male,group E,some high school,standard,none,94,88,78,90
172,female,group D,some college,standard,none,79,86,81,90
173,female,group C,associate's degree,standard,none,63,67,70,90
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,90
175,female,group C,master's degree,standard,completed,81,91,87,90
176,female,group B,high school,free/reduced,completed,46,54,58,90
177,female,group C,associate's degree,standard,completed,71,77,77,90
178,female,group B,master's degree,free/reduced,completed,52,70,62,90
179,female,group D,some high school,standard,completed,97,100,100,90
180,male,group C,master's degree,free/reduced,completed,62,68,75,90
181,female,group C,some college,free/reduced,none,46,64,66,90
182,female,group E,high school,standard,none,50,50,47,90
183,female,group D,associate's degree,standard,none,65,69,70,90
184,male,group C,some high school,free/reduced,completed,45,52,49,90
185,male,group C,associate's degree,free/reduced,completed,65,67,65,90
186,male,group E,high school,standard,none,80,76,65,90
187,male,group D,some high school,standard,completed,62,66,68,90
188,male,group B,some high school,free/reduced,none,48,52,45,90
189,female,group C,bachelor's degree,standard,none,77,88,87,90
190,female,group E,associate's degree,standard,none,66,65,69,90
191,male,group D,some college,standard,completed,76,83,79,90
192,female,group B,some high school,standard,none,62,64,66,90
193,male,group D,some college,standard,completed,77,62,62,90
194,female,group C,master's degree,standard,completed,69,84,85,90
195,male,group D,associate's degree,standard,none,61,55,52,90
196,male,group C,some high school,free/reduced,completed,59,69,65,90
197,male,group E,high school,free/reduced,none,55,56,51,90
198,female,group B,some college,free/reduced,none,45,53,55,90
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,90
200,female,group C,associate's degree,standard,completed,67,84,86,90
201,female,group D,some college,free/reduced,none,65,81,77,90
202,male,group C,associate's degree,standard,none,69,77,69,90
203,female,group B,associate's degree,standard,none,57,69,68,90
204,male,group C,some college,standard,none,59,41,42,90
205,male,group D,some high school,standard,completed,74,71,78,90
206,male,group E,bachelor's degree,standard,none,82,62,62,90
207,male,group E,high school,standard,completed,81,80,76,90
208,female,group B,some college,free/reduced,none,74,81,76,90
209,female,group B,some college,free/reduced,none,58,61,66,90
210,male,group D,some high school,free/reduced,completed,80,79,79,90
211,male,group C,some college,free/reduced,none,35,28,27,90
212,female,group C,high school,free/reduced,none,42,62,60,90
213,male,group C,associate's degree,free/reduced,completed,60,51,56,90
214,male,group E,high school,standard,completed,87,91,81,90
215,male,group B,some high school,standard,completed,84,83,75,90
216,female,group E,associate's degree,free/reduced,completed,83,86,88,90
217,female,group C,high school,free/reduced,none,34,42,39,90
218,male,group B,high school,free/reduced,none,66,77,70,90
219,male,group B,some high school,standard,completed,61,56,56,90
220,female,group D,high school,standard,completed,56,68,74,90
221,male,group B,associate's degree,standard,none,87,85,73,90
222,female,group C,some high school,free/reduced,none,55,65,62,90
223,male,group D,some high school,standard,none,86,80,75,90
224,female,group B,associate's degree,standard,completed,52,66,73,90
225,female,group E,master's degree,free/reduced,none,45,56,54,90
226,female,group C,some college,standard,none,72,72,71,90
227,male,group D,high school,standard,none,57,50,54,90
228,male,group A,some high school,free/reduced,none,68,72,64,90
229,female,group C,some college,standard,completed,88,95,94,90
230,male,group D,some college,standard,none,76,64,66,90
231,male,group C,associate's degree,standard,none,46,43,42,90
232,female,group B,bachelor's degree,standard,none,67,86,83,90
233,male,group E,some high school,standard,none,92,87,78,90
234,male,group C,bachelor's degree,standard,completed,83,82,84,90
235,male,group D,associate's degree,standard,none,80,75,77,90
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,90
237,female,group D,some high school,standard,completed,64,60,74,90
238,male,group B,some college,standard,none,54,52,51,90
239,male,group C,associate's degree,standard,none,84,80,80,90
240,male,group D,high school,free/reduced,completed,73,68,66,90
241,female,group E,bachelor's degree,standard,none,80,83,83,90
242,female,group D,high school,standard,none,56,52,55,90
243,male,group E,some college,standard,none,59,51,43,90
244,male,group D,some high school,standard,none,75,74,69,90
245,male,group C,associate's degree,standard,none,85,76,71,90
246,male,group E,associate's degree,standard,none,89,76,74,90
247,female,group B,high school,standard,completed,58,70,68,90
248,female,group B,high school,standard,none,65,64,62,90
249,male,group C,high school,standard,none,68,60,53,90
250,male,group A,some high school,standard,completed,47,49,49,90
251,female,group D,some college,free/reduced,none,71,83,83,90
252,female,group B,some high school,standard,completed,60,70,70,90
253,male,group D,master's degree,standard,none,80,80,72,90
254,male,group D,high school,standard,none,54,52,52,90
255,female,group E,some college,standard,none,62,73,70,90
256,female,group C,associate's degree,free/reduced,none,64,73,68,90
257,male,group C,associate's degree,standard,completed,78,77,77,90
258,female,group B,some college,standard,none,70,75,78,90
259,female,group C,master's degree,free/reduced,completed,65,81,81,90
260,female,group C,some high school,free/reduced,completed,64,79,77,90
261,male,group C,some college,standard,completed,79,79,78,90
262,female,group C,some high school,free/reduced,none,44,50,51,90
263,female,group E,high school,standard,none,99,93,90,90
264,male,group D,high school,standard,none,76,73,68,90
265,male,group D,some high school,free/reduced,none,59,42,41,90
266,female,group C,bachelor's degree,standard,none,63,75,81,90
267,female,group D,high school,standard,none,69,72,77,90
268,female,group D,associate's degree,standard,completed,88,92,95,90
269,female,group E,some college,free/reduced,none,71,76,70,90
270,male,group C,bachelor's degree,standard,none,69,63,61,90
271,male,group C,some college,standard,none,58,49,42,90
272,female,group D,associate's degree,free/reduced,none,47,53,58,90
273,female,group D,some college,standard,none,65,70,71,90
274,male,group B,some college,standard,completed,88,85,76,90
275,male,group C,bachelor's degree,standard,none,83,78,73,90
276,female,group C,some high school,standard,completed,85,92,93,90
277,female,group E,high school,standard,completed,59,63,75,90
278,female,group C,some high school,free/reduced,none,65,86,80,90
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,90
280,male,group D,high school,standard,none,53,52,42,90
281,male,group D,high school,standard,none,45,48,46,90
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,90
283,female,group D,some college,free/reduced,completed,70,78,78,90
284,female,group B,some high school,standard,none,37,46,46,90
285,male,group B,associate's degree,standard,completed,81,82,82,90
286,male,group E,associate's degree,standard,completed,97,82,88,90
287,female,group B,some high school,standard,none,67,89,82,90
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,90
289,male,group E,some high school,standard,completed,77,76,77,90
290,male,group C,associate's degree,standard,none,76,70,68,90
291,male,group D,some high school,standard,none,86,73,70,90
292,male,group C,some high school,standard,completed,63,60,57,90
293,female,group E,bachelor's degree,standard,none,65,73,75,90
294,male,group D,high school,free/reduced,completed,78,77,80,90
295,male,group B,associate's degree,free/reduced,none,67,62,60,90
296,male,group A,some high school,standard,completed,46,41,43,90
297,male,group E,associate's degree,standard,completed,71,74,68,90
298,male,group C,high school,free/reduced,completed,40,46,50,90
299,male,group D,associate's degree,free/reduced,none,90,87,75,90
300,male,group A,some college,free/reduced,completed,81,78,81,90
301,male,group D,some high school,free/reduced,none,56,54,52,90
302,female,group C,associate's degree,standard,completed,67,84,81,90
303,male,group B,associate's degree,standard,none,80,76,64,90
304,female,group C,associate's degree,standard,completed,74,75,83,90
305,male,group A,some college,standard,none,69,67,69,90
306,male,group E,some college,standard,completed,99,87,81,90
307,male,group C,some high school,standard,none,51,52,44,90
308,female,group B,associate's degree,free/reduced,none,53,71,67,90
309,female,group D,high school,free/reduced,none,49,57,52,90
310,female,group B,associate's degree,standard,none,73,76,80,90
311,male,group B,bachelor's degree,standard,none,66,60,57,90
312,male,group D,bachelor's degree,standard,completed,67,61,68,90
313,female,group C,associate's degree,free/reduced,completed,68,67,69,90
314,female,group C,bachelor's degree,standard,completed,59,64,75,90
315,male,group C,high school,standard,none,71,66,65,90
316,female,group D,master's degree,standard,completed,77,82,91,90

In [43]:
#adding new column with an array
import numpy as np

In [44]:
language_score=np.arange(0,1000)

In [45]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,90
1,female,group C,some college,standard,completed,69,90,88,90
2,female,group B,master's degree,standard,none,90,95,93,90
3,male,group A,associate's degree,free/reduced,none,47,57,44,90
4,male,group C,some college,standard,none,76,78,75,90
5,female,group B,associate's degree,standard,none,71,83,78,90
6,female,group B,some college,standard,completed,88,95,92,90
7,male,group B,some college,free/reduced,none,40,43,39,90
8,male,group D,high school,free/reduced,completed,64,64,67,90
9,female,group B,high school,free/reduced,none,38,60,50,90
10,male,group C,associate's degree,standard,none,58,54,52,90
11,male,group D,associate's degree,standard,none,40,52,43,90
12,female,group B,high school,standard,none,65,81,73,90
13,male,group A,some college,standard,completed,78,72,70,90
14,female,group A,master's degree,standard,none,50,53,58,90
15,female,group C,some high school,standard,none,69,75,78,90
16,male,group C,high school,standard,none,88,89,86,90
17,female,group B,some high school,free/reduced,none,18,32,28,90
18,male,group C,master's degree,free/reduced,completed,46,42,46,90
19,female,group C,associate's degree,free/reduced,none,54,58,61,90
20,male,group D,high school,standard,none,66,69,63,90
21,female,group B,some college,free/reduced,completed,65,75,70,90
22,male,group D,some college,standard,none,44,54,53,90
23,female,group C,some high school,standard,none,69,73,73,90
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,90
25,male,group A,master's degree,free/reduced,none,73,74,72,90
26,male,group B,some college,standard,none,69,54,55,90
27,female,group C,bachelor's degree,standard,none,67,69,75,90
28,male,group C,high school,standard,none,70,70,65,90
29,female,group D,master's degree,standard,none,62,70,75,90
30,female,group D,some college,standard,none,69,74,74,90
31,female,group B,some college,standard,none,63,65,61,90
32,female,group E,master's degree,free/reduced,none,56,72,65,90
33,male,group D,some college,standard,none,40,42,38,90
34,male,group E,some college,standard,none,97,87,82,90
35,male,group E,associate's degree,standard,completed,81,81,79,90
36,female,group D,associate's degree,standard,none,74,81,83,90
37,female,group D,some high school,free/reduced,none,50,64,59,90
38,female,group D,associate's degree,free/reduced,completed,75,90,88,90
39,male,group B,associate's degree,free/reduced,none,57,56,57,90
40,male,group C,associate's degree,free/reduced,none,55,61,54,90
41,female,group C,associate's degree,standard,none,58,73,68,90
42,female,group B,associate's degree,standard,none,53,58,65,90
43,male,group B,some college,free/reduced,completed,59,65,66,90
44,female,group E,associate's degree,free/reduced,none,50,56,54,90
45,male,group B,associate's degree,standard,none,65,54,57,90
46,female,group A,associate's degree,standard,completed,55,65,62,90
47,female,group C,high school,standard,none,66,71,76,90
48,female,group D,associate's degree,free/reduced,completed,57,74,76,90
49,male,group C,high school,standard,completed,82,84,82,90
50,male,group E,some college,standard,none,53,55,48,90
51,male,group E,associate's degree,free/reduced,completed,77,69,68,90
52,male,group C,some college,standard,none,53,44,42,90
53,male,group D,high school,standard,none,88,78,75,90
54,female,group C,some high school,free/reduced,completed,71,84,87,90
55,female,group C,high school,free/reduced,none,33,41,43,90
56,female,group E,associate's degree,standard,completed,82,85,86,90
57,male,group D,associate's degree,standard,none,52,55,49,90
58,male,group D,some college,standard,completed,58,59,58,90
59,female,group C,some high school,free/reduced,none,0,17,10,90
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,90
61,male,group A,some high school,free/reduced,none,39,39,34,90
62,male,group A,associate's degree,free/reduced,none,62,61,55,90
63,female,group C,associate's degree,standard,none,69,80,71,90
64,female,group D,some high school,standard,none,59,58,59,90
65,male,group B,some high school,standard,none,67,64,61,90
66,male,group D,some high school,free/reduced,none,45,37,37,90
67,female,group C,some college,standard,none,60,72,74,90
68,male,group B,associate's degree,free/reduced,none,61,58,56,90
69,female,group C,associate's degree,standard,none,39,64,57,90
70,female,group D,some college,free/reduced,completed,58,63,73,90
71,male,group D,some college,standard,completed,63,55,63,90
72,female,group A,associate's degree,free/reduced,none,41,51,48,90
73,male,group C,some high school,free/reduced,none,61,57,56,90
74,male,group C,some high school,standard,none,49,49,41,90
75,male,group B,associate's degree,free/reduced,none,44,41,38,90
76,male,group E,some high school,standard,none,30,26,22,90
77,male,group A,bachelor's degree,standard,completed,80,78,81,90
78,female,group D,some high school,standard,completed,61,74,72,90
79,female,group E,master's degree,standard,none,62,68,68,90
80,female,group B,associate's degree,standard,none,47,49,50,90
81,male,group B,high school,free/reduced,none,49,45,45,90
82,male,group A,some college,free/reduced,completed,50,47,54,90
83,male,group E,associate's degree,standard,none,72,64,63,90
84,male,group D,high school,free/reduced,none,42,39,34,90
85,female,group C,some college,standard,none,73,80,82,90
86,female,group C,some college,free/reduced,none,76,83,88,90
87,female,group D,associate's degree,standard,none,71,71,74,90
88,female,group A,some college,standard,none,58,70,67,90
89,female,group D,some high school,standard,none,73,86,82,90
90,female,group C,bachelor's degree,standard,none,65,72,74,90
91,male,group C,high school,free/reduced,none,27,34,36,90
92,male,group C,high school,standard,none,71,79,71,90
93,male,group C,associate's degree,free/reduced,completed,43,45,50,90
94,female,group B,some college,standard,none,79,86,92,90
95,male,group C,associate's degree,free/reduced,completed,78,81,82,90
96,male,group B,some high school,standard,completed,65,66,62,90
97,female,group E,some college,standard,completed,63,72,70,90
98,female,group D,some college,free/reduced,none,58,67,62,90
99,female,group D,bachelor's degree,standard,none,65,67,62,90
100,male,group B,some college,standard,none,79,67,67,90
101,male,group D,bachelor's degree,standard,completed,68,74,74,90
102,female,group D,associate's degree,standard,none,85,91,89,90
103,male,group B,high school,standard,completed,60,44,47,90
104,male,group C,some college,standard,completed,98,86,90,90
105,female,group C,some college,standard,none,58,67,72,90
106,female,group D,master's degree,standard,none,87,100,100,90
107,male,group E,associate's degree,standard,completed,66,63,64,90
108,female,group B,associate's degree,free/reduced,none,52,76,70,90
109,female,group B,some high school,standard,none,70,64,72,90
110,female,group D,associate's degree,free/reduced,completed,77,89,98,90
111,male,group C,high school,standard,none,62,55,49,90
112,male,group A,associate's degree,standard,none,54,53,47,90
113,female,group D,some college,standard,none,51,58,54,90
114,female,group E,bachelor's degree,standard,completed,99,100,100,90
115,male,group C,high school,standard,none,84,77,74,90
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,90
117,female,group D,bachelor's degree,standard,none,78,82,79,90
118,female,group D,some high school,standard,none,51,63,61,90
119,female,group C,some college,standard,none,55,69,65,90
120,female,group C,bachelor's degree,standard,completed,79,92,89,90
121,male,group B,associate's degree,standard,completed,91,89,92,90
122,female,group C,some college,standard,completed,88,93,93,90
123,male,group D,high school,free/reduced,none,63,57,56,90
124,male,group E,some college,standard,none,83,80,73,90
125,female,group B,high school,standard,none,87,95,86,90
126,male,group B,some high school,standard,none,72,68,67,90
127,male,group D,some college,standard,completed,65,77,74,90
128,male,group D,master's degree,standard,none,82,82,74,90
129,female,group A,bachelor's degree,standard,none,51,49,51,90
130,male,group D,master's degree,standard,none,89,84,82,90
131,male,group C,some high school,free/reduced,completed,53,37,40,90
132,male,group E,some college,free/reduced,completed,87,74,70,90
133,female,group C,some college,standard,completed,75,81,84,90
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,90
135,male,group C,bachelor's degree,standard,none,58,55,48,90
136,male,group B,some high school,standard,completed,51,54,41,90
137,male,group E,high school,standard,none,70,55,56,90
138,female,group C,associate's degree,standard,none,59,66,67,90
139,male,group D,some college,standard,completed,71,61,69,90
140,female,group D,some high school,standard,none,76,72,71,90
141,female,group C,some college,free/reduced,none,59,62,64,90
142,female,group E,some college,free/reduced,completed,42,55,54,90
143,male,group A,high school,standard,none,57,43,47,90
144,male,group D,some college,standard,none,88,73,78,90
145,female,group C,some college,free/reduced,none,22,39,33,90
146,male,group B,some high school,standard,none,88,84,75,90
147,male,group C,associate's degree,free/reduced,none,73,68,66,90
148,female,group D,bachelor's degree,standard,completed,68,75,81,90
149,male,group E,associate's degree,free/reduced,completed,100,100,93,90
150,male,group A,some high school,standard,completed,62,67,69,90
151,male,group A,bachelor's degree,standard,none,77,67,68,90
152,female,group B,associate's degree,standard,completed,59,70,66,90
153,male,group D,bachelor's degree,standard,none,54,49,47,90
154,male,group D,some high school,standard,none,62,67,61,90
155,female,group C,some college,standard,completed,70,89,88,90
156,female,group E,high school,free/reduced,completed,66,74,78,90
157,male,group B,some college,free/reduced,none,60,60,60,90
158,female,group B,associate's degree,standard,completed,61,86,87,90
159,male,group D,associate's degree,free/reduced,none,66,62,64,90
160,male,group B,associate's degree,free/reduced,completed,82,78,74,90
161,female,group E,some college,free/reduced,completed,75,88,85,90
162,male,group B,master's degree,free/reduced,none,49,53,52,90
163,male,group C,high school,standard,none,52,53,49,90
164,female,group E,master's degree,standard,none,81,92,91,90
165,female,group C,bachelor's degree,standard,completed,96,100,100,90
166,male,group C,high school,free/reduced,completed,53,51,51,90
167,female,group B,master's degree,free/reduced,completed,58,76,78,90
168,female,group B,high school,standard,completed,68,83,78,90
169,female,group C,some college,free/reduced,completed,67,75,70,90
170,male,group A,high school,standard,completed,72,73,74,90
171,male,group E,some high school,standard,none,94,88,78,90
172,female,group D,some college,standard,none,79,86,81,90
173,female,group C,associate's degree,standard,none,63,67,70,90
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,90
175,female,group C,master's degree,standard,completed,81,91,87,90
176,female,group B,high school,free/reduced,completed,46,54,58,90
177,female,group C,associate's degree,standard,completed,71,77,77,90
178,female,group B,master's degree,free/reduced,completed,52,70,62,90
179,female,group D,some high school,standard,completed,97,100,100,90
180,male,group C,master's degree,free/reduced,completed,62,68,75,90
181,female,group C,some college,free/reduced,none,46,64,66,90
182,female,group E,high school,standard,none,50,50,47,90
183,female,group D,associate's degree,standard,none,65,69,70,90
184,male,group C,some high school,free/reduced,completed,45,52,49,90
185,male,group C,associate's degree,free/reduced,completed,65,67,65,90
186,male,group E,high school,standard,none,80,76,65,90
187,male,group D,some high school,standard,completed,62,66,68,90
188,male,group B,some high school,free/reduced,none,48,52,45,90
189,female,group C,bachelor's degree,standard,none,77,88,87,90
190,female,group E,associate's degree,standard,none,66,65,69,90
191,male,group D,some college,standard,completed,76,83,79,90
192,female,group B,some high school,standard,none,62,64,66,90
193,male,group D,some college,standard,completed,77,62,62,90
194,female,group C,master's degree,standard,completed,69,84,85,90
195,male,group D,associate's degree,standard,none,61,55,52,90
196,male,group C,some high school,free/reduced,completed,59,69,65,90
197,male,group E,high school,free/reduced,none,55,56,51,90
198,female,group B,some college,free/reduced,none,45,53,55,90
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,90
200,female,group C,associate's degree,standard,completed,67,84,86,90
201,female,group D,some college,free/reduced,none,65,81,77,90
202,male,group C,associate's degree,standard,none,69,77,69,90
203,female,group B,associate's degree,standard,none,57,69,68,90
204,male,group C,some college,standard,none,59,41,42,90
205,male,group D,some high school,standard,completed,74,71,78,90
206,male,group E,bachelor's degree,standard,none,82,62,62,90
207,male,group E,high school,standard,completed,81,80,76,90
208,female,group B,some college,free/reduced,none,74,81,76,90
209,female,group B,some college,free/reduced,none,58,61,66,90
210,male,group D,some high school,free/reduced,completed,80,79,79,90
211,male,group C,some college,free/reduced,none,35,28,27,90
212,female,group C,high school,free/reduced,none,42,62,60,90
213,male,group C,associate's degree,free/reduced,completed,60,51,56,90
214,male,group E,high school,standard,completed,87,91,81,90
215,male,group B,some high school,standard,completed,84,83,75,90
216,female,group E,associate's degree,free/reduced,completed,83,86,88,90
217,female,group C,high school,free/reduced,none,34,42,39,90
218,male,group B,high school,free/reduced,none,66,77,70,90
219,male,group B,some high school,standard,completed,61,56,56,90
220,female,group D,high school,standard,completed,56,68,74,90
221,male,group B,associate's degree,standard,none,87,85,73,90
222,female,group C,some high school,free/reduced,none,55,65,62,90
223,male,group D,some high school,standard,none,86,80,75,90
224,female,group B,associate's degree,standard,completed,52,66,73,90
225,female,group E,master's degree,free/reduced,none,45,56,54,90
226,female,group C,some college,standard,none,72,72,71,90
227,male,group D,high school,standard,none,57,50,54,90
228,male,group A,some high school,free/reduced,none,68,72,64,90
229,female,group C,some college,standard,completed,88,95,94,90
230,male,group D,some college,standard,none,76,64,66,90
231,male,group C,associate's degree,standard,none,46,43,42,90
232,female,group B,bachelor's degree,standard,none,67,86,83,90
233,male,group E,some high school,standard,none,92,87,78,90
234,male,group C,bachelor's degree,standard,completed,83,82,84,90
235,male,group D,associate's degree,standard,none,80,75,77,90
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,90
237,female,group D,some high school,standard,completed,64,60,74,90
238,male,group B,some college,standard,none,54,52,51,90
239,male,group C,associate's degree,standard,none,84,80,80,90
240,male,group D,high school,free/reduced,completed,73,68,66,90
241,female,group E,bachelor's degree,standard,none,80,83,83,90
242,female,group D,high school,standard,none,56,52,55,90
243,male,group E,some college,standard,none,59,51,43,90
244,male,group D,some high school,standard,none,75,74,69,90
245,male,group C,associate's degree,standard,none,85,76,71,90
246,male,group E,associate's degree,standard,none,89,76,74,90
247,female,group B,high school,standard,completed,58,70,68,90
248,female,group B,high school,standard,none,65,64,62,90
249,male,group C,high school,standard,none,68,60,53,90
250,male,group A,some high school,standard,completed,47,49,49,90
251,female,group D,some college,free/reduced,none,71,83,83,90
252,female,group B,some high school,standard,completed,60,70,70,90
253,male,group D,master's degree,standard,none,80,80,72,90
254,male,group D,high school,standard,none,54,52,52,90
255,female,group E,some college,standard,none,62,73,70,90
256,female,group C,associate's degree,free/reduced,none,64,73,68,90
257,male,group C,associate's degree,standard,completed,78,77,77,90
258,female,group B,some college,standard,none,70,75,78,90
259,female,group C,master's degree,free/reduced,completed,65,81,81,90
260,female,group C,some high school,free/reduced,completed,64,79,77,90
261,male,group C,some college,standard,completed,79,79,78,90
262,female,group C,some high school,free/reduced,none,44,50,51,90
263,female,group E,high school,standard,none,99,93,90,90
264,male,group D,high school,standard,none,76,73,68,90
265,male,group D,some high school,free/reduced,none,59,42,41,90
266,female,group C,bachelor's degree,standard,none,63,75,81,90
267,female,group D,high school,standard,none,69,72,77,90
268,female,group D,associate's degree,standard,completed,88,92,95,90
269,female,group E,some college,free/reduced,none,71,76,70,90
270,male,group C,bachelor's degree,standard,none,69,63,61,90
271,male,group C,some college,standard,none,58,49,42,90
272,female,group D,associate's degree,free/reduced,none,47,53,58,90
273,female,group D,some college,standard,none,65,70,71,90
274,male,group B,some college,standard,completed,88,85,76,90
275,male,group C,bachelor's degree,standard,none,83,78,73,90
276,female,group C,some high school,standard,completed,85,92,93,90
277,female,group E,high school,standard,completed,59,63,75,90
278,female,group C,some high school,free/reduced,none,65,86,80,90
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,90
280,male,group D,high school,standard,none,53,52,42,90
281,male,group D,high school,standard,none,45,48,46,90
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,90
283,female,group D,some college,free/reduced,completed,70,78,78,90
284,female,group B,some high school,standard,none,37,46,46,90
285,male,group B,associate's degree,standard,completed,81,82,82,90
286,male,group E,associate's degree,standard,completed,97,82,88,90
287,female,group B,some high school,standard,none,67,89,82,90
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,90
289,male,group E,some high school,standard,completed,77,76,77,90
290,male,group C,associate's degree,standard,none,76,70,68,90
291,male,group D,some high school,standard,none,86,73,70,90
292,male,group C,some high school,standard,completed,63,60,57,90
293,female,group E,bachelor's degree,standard,none,65,73,75,90
294,male,group D,high school,free/reduced,completed,78,77,80,90
295,male,group B,associate's degree,free/reduced,none,67,62,60,90
296,male,group A,some high school,standard,completed,46,41,43,90
297,male,group E,associate's degree,standard,completed,71,74,68,90
298,male,group C,high school,free/reduced,completed,40,46,50,90
299,male,group D,associate's degree,free/reduced,none,90,87,75,90
300,male,group A,some college,free/reduced,completed,81,78,81,90
301,male,group D,some high school,free/reduced,none,56,54,52,90
302,female,group C,associate's degree,standard,completed,67,84,81,90
303,male,group B,associate's degree,standard,none,80,76,64,90
304,female,group C,associate's degree,standard,completed,74,75,83,90
305,male,group A,some college,standard,none,69,67,69,90
306,male,group E,some college,standard,completed,99,87,81,90
307,male,group C,some high school,standard,none,51,52,44,90
308,female,group B,associate's degree,free/reduced,none,53,71,67,90
309,female,group D,high school,free/reduced,none,49,57,52,90
310,female,group B,associate's degree,standard,none,73,76,80,90
311,male,group B,bachelor's degree,standard,none,66,60,57,90
312,male,group D,bachelor's degree,standard,completed,67,61,68,90
313,female,group C,associate's degree,free/reduced,completed,68,67,69,90
314,female,group C,bachelor's degree,standard,completed,59,64,75,90
315,male,group C,high school,standard,none,71,66,65,90
316,female,group D,master's degree,standard,completed,77,82,91,90

In [46]:
len(language_score)

1000

In [47]:
df['language score']=language_score

In [48]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
5,female,group B,associate's degree,standard,none,71,83,78,5
6,female,group B,some college,standard,completed,88,95,92,6
7,male,group B,some college,free/reduced,none,40,43,39,7
8,male,group D,high school,free/reduced,completed,64,64,67,8
9,female,group B,high school,free/reduced,none,38,60,50,9
10,male,group C,associate's degree,standard,none,58,54,52,10
11,male,group D,associate's degree,standard,none,40,52,43,11
12,female,group B,high school,standard,none,65,81,73,12
13,male,group A,some college,standard,completed,78,72,70,13
14,female,group A,master's degree,standard,none,50,53,58,14
15,female,group C,some high school,standard,none,69,75,78,15
16,male,group C,high school,standard,none,88,89,86,16
17,female,group B,some high school,free/reduced,none,18,32,28,17
18,male,group C,master's degree,free/reduced,completed,46,42,46,18
19,female,group C,associate's degree,free/reduced,none,54,58,61,19
20,male,group D,high school,standard,none,66,69,63,20
21,female,group B,some college,free/reduced,completed,65,75,70,21
22,male,group D,some college,standard,none,44,54,53,22
23,female,group C,some high school,standard,none,69,73,73,23
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,24
25,male,group A,master's degree,free/reduced,none,73,74,72,25
26,male,group B,some college,standard,none,69,54,55,26
27,female,group C,bachelor's degree,standard,none,67,69,75,27
28,male,group C,high school,standard,none,70,70,65,28
29,female,group D,master's degree,standard,none,62,70,75,29
30,female,group D,some college,standard,none,69,74,74,30
31,female,group B,some college,standard,none,63,65,61,31
32,female,group E,master's degree,free/reduced,none,56,72,65,32
33,male,group D,some college,standard,none,40,42,38,33
34,male,group E,some college,standard,none,97,87,82,34
35,male,group E,associate's degree,standard,completed,81,81,79,35
36,female,group D,associate's degree,standard,none,74,81,83,36
37,female,group D,some high school,free/reduced,none,50,64,59,37
38,female,group D,associate's degree,free/reduced,completed,75,90,88,38
39,male,group B,associate's degree,free/reduced,none,57,56,57,39
40,male,group C,associate's degree,free/reduced,none,55,61,54,40
41,female,group C,associate's degree,standard,none,58,73,68,41
42,female,group B,associate's degree,standard,none,53,58,65,42
43,male,group B,some college,free/reduced,completed,59,65,66,43
44,female,group E,associate's degree,free/reduced,none,50,56,54,44
45,male,group B,associate's degree,standard,none,65,54,57,45
46,female,group A,associate's degree,standard,completed,55,65,62,46
47,female,group C,high school,standard,none,66,71,76,47
48,female,group D,associate's degree,free/reduced,completed,57,74,76,48
49,male,group C,high school,standard,completed,82,84,82,49
50,male,group E,some college,standard,none,53,55,48,50
51,male,group E,associate's degree,free/reduced,completed,77,69,68,51
52,male,group C,some college,standard,none,53,44,42,52
53,male,group D,high school,standard,none,88,78,75,53
54,female,group C,some high school,free/reduced,completed,71,84,87,54
55,female,group C,high school,free/reduced,none,33,41,43,55
56,female,group E,associate's degree,standard,completed,82,85,86,56
57,male,group D,associate's degree,standard,none,52,55,49,57
58,male,group D,some college,standard,completed,58,59,58,58
59,female,group C,some high school,free/reduced,none,0,17,10,59
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,60
61,male,group A,some high school,free/reduced,none,39,39,34,61
62,male,group A,associate's degree,free/reduced,none,62,61,55,62
63,female,group C,associate's degree,standard,none,69,80,71,63
64,female,group D,some high school,standard,none,59,58,59,64
65,male,group B,some high school,standard,none,67,64,61,65
66,male,group D,some high school,free/reduced,none,45,37,37,66
67,female,group C,some college,standard,none,60,72,74,67
68,male,group B,associate's degree,free/reduced,none,61,58,56,68
69,female,group C,associate's degree,standard,none,39,64,57,69
70,female,group D,some college,free/reduced,completed,58,63,73,70
71,male,group D,some college,standard,completed,63,55,63,71
72,female,group A,associate's degree,free/reduced,none,41,51,48,72
73,male,group C,some high school,free/reduced,none,61,57,56,73
74,male,group C,some high school,standard,none,49,49,41,74
75,male,group B,associate's degree,free/reduced,none,44,41,38,75
76,male,group E,some high school,standard,none,30,26,22,76
77,male,group A,bachelor's degree,standard,completed,80,78,81,77
78,female,group D,some high school,standard,completed,61,74,72,78
79,female,group E,master's degree,standard,none,62,68,68,79
80,female,group B,associate's degree,standard,none,47,49,50,80
81,male,group B,high school,free/reduced,none,49,45,45,81
82,male,group A,some college,free/reduced,completed,50,47,54,82
83,male,group E,associate's degree,standard,none,72,64,63,83
84,male,group D,high school,free/reduced,none,42,39,34,84
85,female,group C,some college,standard,none,73,80,82,85
86,female,group C,some college,free/reduced,none,76,83,88,86
87,female,group D,associate's degree,standard,none,71,71,74,87
88,female,group A,some college,standard,none,58,70,67,88
89,female,group D,some high school,standard,none,73,86,82,89
90,female,group C,bachelor's degree,standard,none,65,72,74,90
91,male,group C,high school,free/reduced,none,27,34,36,91
92,male,group C,high school,standard,none,71,79,71,92
93,male,group C,associate's degree,free/reduced,completed,43,45,50,93
94,female,group B,some college,standard,none,79,86,92,94
95,male,group C,associate's degree,free/reduced,completed,78,81,82,95
96,male,group B,some high school,standard,completed,65,66,62,96
97,female,group E,some college,standard,completed,63,72,70,97
98,female,group D,some college,free/reduced,none,58,67,62,98
99,female,group D,bachelor's degree,standard,none,65,67,62,99
100,male,group B,some college,standard,none,79,67,67,100
101,male,group D,bachelor's degree,standard,completed,68,74,74,101
102,female,group D,associate's degree,standard,none,85,91,89,102
103,male,group B,high school,standard,completed,60,44,47,103
104,male,group C,some college,standard,completed,98,86,90,104
105,female,group C,some college,standard,none,58,67,72,105
106,female,group D,master's degree,standard,none,87,100,100,106
107,male,group E,associate's degree,standard,completed,66,63,64,107
108,female,group B,associate's degree,free/reduced,none,52,76,70,108
109,female,group B,some high school,standard,none,70,64,72,109
110,female,group D,associate's degree,free/reduced,completed,77,89,98,110
111,male,group C,high school,standard,none,62,55,49,111
112,male,group A,associate's degree,standard,none,54,53,47,112
113,female,group D,some college,standard,none,51,58,54,113
114,female,group E,bachelor's degree,standard,completed,99,100,100,114
115,male,group C,high school,standard,none,84,77,74,115
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,116
117,female,group D,bachelor's degree,standard,none,78,82,79,117
118,female,group D,some high school,standard,none,51,63,61,118
119,female,group C,some college,standard,none,55,69,65,119
120,female,group C,bachelor's degree,standard,completed,79,92,89,120
121,male,group B,associate's degree,standard,completed,91,89,92,121
122,female,group C,some college,standard,completed,88,93,93,122
123,male,group D,high school,free/reduced,none,63,57,56,123
124,male,group E,some college,standard,none,83,80,73,124
125,female,group B,high school,standard,none,87,95,86,125
126,male,group B,some high school,standard,none,72,68,67,126
127,male,group D,some college,standard,completed,65,77,74,127
128,male,group D,master's degree,standard,none,82,82,74,128
129,female,group A,bachelor's degree,standard,none,51,49,51,129
130,male,group D,master's degree,standard,none,89,84,82,130
131,male,group C,some high school,free/reduced,completed,53,37,40,131
132,male,group E,some college,free/reduced,completed,87,74,70,132
133,female,group C,some college,standard,completed,75,81,84,133
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,134
135,male,group C,bachelor's degree,standard,none,58,55,48,135
136,male,group B,some high school,standard,completed,51,54,41,136
137,male,group E,high school,standard,none,70,55,56,137
138,female,group C,associate's degree,standard,none,59,66,67,138
139,male,group D,some college,standard,completed,71,61,69,139
140,female,group D,some high school,standard,none,76,72,71,140
141,female,group C,some college,free/reduced,none,59,62,64,141
142,female,group E,some college,free/reduced,completed,42,55,54,142
143,male,group A,high school,standard,none,57,43,47,143
144,male,group D,some college,standard,none,88,73,78,144
145,female,group C,some college,free/reduced,none,22,39,33,145
146,male,group B,some high school,standard,none,88,84,75,146
147,male,group C,associate's degree,free/reduced,none,73,68,66,147
148,female,group D,bachelor's degree,standard,completed,68,75,81,148
149,male,group E,associate's degree,free/reduced,completed,100,100,93,149
150,male,group A,some high school,standard,completed,62,67,69,150
151,male,group A,bachelor's degree,standard,none,77,67,68,151
152,female,group B,associate's degree,standard,completed,59,70,66,152
153,male,group D,bachelor's degree,standard,none,54,49,47,153
154,male,group D,some high school,standard,none,62,67,61,154
155,female,group C,some college,standard,completed,70,89,88,155
156,female,group E,high school,free/reduced,completed,66,74,78,156
157,male,group B,some college,free/reduced,none,60,60,60,157
158,female,group B,associate's degree,standard,completed,61,86,87,158
159,male,group D,associate's degree,free/reduced,none,66,62,64,159
160,male,group B,associate's degree,free/reduced,completed,82,78,74,160
161,female,group E,some college,free/reduced,completed,75,88,85,161
162,male,group B,master's degree,free/reduced,none,49,53,52,162
163,male,group C,high school,standard,none,52,53,49,163
164,female,group E,master's degree,standard,none,81,92,91,164
165,female,group C,bachelor's degree,standard,completed,96,100,100,165
166,male,group C,high school,free/reduced,completed,53,51,51,166
167,female,group B,master's degree,free/reduced,completed,58,76,78,167
168,female,group B,high school,standard,completed,68,83,78,168
169,female,group C,some college,free/reduced,completed,67,75,70,169
170,male,group A,high school,standard,completed,72,73,74,170
171,male,group E,some high school,standard,none,94,88,78,171
172,female,group D,some college,standard,none,79,86,81,172
173,female,group C,associate's degree,standard,none,63,67,70,173
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,174
175,female,group C,master's degree,standard,completed,81,91,87,175
176,female,group B,high school,free/reduced,completed,46,54,58,176
177,female,group C,associate's degree,standard,completed,71,77,77,177
178,female,group B,master's degree,free/reduced,completed,52,70,62,178
179,female,group D,some high school,standard,completed,97,100,100,179
180,male,group C,master's degree,free/reduced,completed,62,68,75,180
181,female,group C,some college,free/reduced,none,46,64,66,181
182,female,group E,high school,standard,none,50,50,47,182
183,female,group D,associate's degree,standard,none,65,69,70,183
184,male,group C,some high school,free/reduced,completed,45,52,49,184
185,male,group C,associate's degree,free/reduced,completed,65,67,65,185
186,male,group E,high school,standard,none,80,76,65,186
187,male,group D,some high school,standard,completed,62,66,68,187
188,male,group B,some high school,free/reduced,none,48,52,45,188
189,female,group C,bachelor's degree,standard,none,77,88,87,189
190,female,group E,associate's degree,standard,none,66,65,69,190
191,male,group D,some college,standard,completed,76,83,79,191
192,female,group B,some high school,standard,none,62,64,66,192
193,male,group D,some college,standard,completed,77,62,62,193
194,female,group C,master's degree,standard,completed,69,84,85,194
195,male,group D,associate's degree,standard,none,61,55,52,195
196,male,group C,some high school,free/reduced,completed,59,69,65,196
197,male,group E,high school,free/reduced,none,55,56,51,197
198,female,group B,some college,free/reduced,none,45,53,55,198
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,199
200,female,group C,associate's degree,standard,completed,67,84,86,200
201,female,group D,some college,free/reduced,none,65,81,77,201
202,male,group C,associate's degree,standard,none,69,77,69,202
203,female,group B,associate's degree,standard,none,57,69,68,203
204,male,group C,some college,standard,none,59,41,42,204
205,male,group D,some high school,standard,completed,74,71,78,205
206,male,group E,bachelor's degree,standard,none,82,62,62,206
207,male,group E,high school,standard,completed,81,80,76,207
208,female,group B,some college,free/reduced,none,74,81,76,208
209,female,group B,some college,free/reduced,none,58,61,66,209
210,male,group D,some high school,free/reduced,completed,80,79,79,210
211,male,group C,some college,free/reduced,none,35,28,27,211
212,female,group C,high school,free/reduced,none,42,62,60,212
213,male,group C,associate's degree,free/reduced,completed,60,51,56,213
214,male,group E,high school,standard,completed,87,91,81,214
215,male,group B,some high school,standard,completed,84,83,75,215
216,female,group E,associate's degree,free/reduced,completed,83,86,88,216
217,female,group C,high school,free/reduced,none,34,42,39,217
218,male,group B,high school,free/reduced,none,66,77,70,218
219,male,group B,some high school,standard,completed,61,56,56,219
220,female,group D,high school,standard,completed,56,68,74,220
221,male,group B,associate's degree,standard,none,87,85,73,221
222,female,group C,some high school,free/reduced,none,55,65,62,222
223,male,group D,some high school,standard,none,86,80,75,223
224,female,group B,associate's degree,standard,completed,52,66,73,224
225,female,group E,master's degree,free/reduced,none,45,56,54,225
226,female,group C,some college,standard,none,72,72,71,226
227,male,group D,high school,standard,none,57,50,54,227
228,male,group A,some high school,free/reduced,none,68,72,64,228
229,female,group C,some college,standard,completed,88,95,94,229
230,male,group D,some college,standard,none,76,64,66,230
231,male,group C,associate's degree,standard,none,46,43,42,231
232,female,group B,bachelor's degree,standard,none,67,86,83,232
233,male,group E,some high school,standard,none,92,87,78,233
234,male,group C,bachelor's degree,standard,completed,83,82,84,234
235,male,group D,associate's degree,standard,none,80,75,77,235
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,236
237,female,group D,some high school,standard,completed,64,60,74,237
238,male,group B,some college,standard,none,54,52,51,238
239,male,group C,associate's degree,standard,none,84,80,80,239
240,male,group D,high school,free/reduced,completed,73,68,66,240
241,female,group E,bachelor's degree,standard,none,80,83,83,241
242,female,group D,high school,standard,none,56,52,55,242
243,male,group E,some college,standard,none,59,51,43,243
244,male,group D,some high school,standard,none,75,74,69,244
245,male,group C,associate's degree,standard,none,85,76,71,245
246,male,group E,associate's degree,standard,none,89,76,74,246
247,female,group B,high school,standard,completed,58,70,68,247
248,female,group B,high school,standard,none,65,64,62,248
249,male,group C,high school,standard,none,68,60,53,249
250,male,group A,some high school,standard,completed,47,49,49,250
251,female,group D,some college,free/reduced,none,71,83,83,251
252,female,group B,some high school,standard,completed,60,70,70,252
253,male,group D,master's degree,standard,none,80,80,72,253
254,male,group D,high school,standard,none,54,52,52,254
255,female,group E,some college,standard,none,62,73,70,255
256,female,group C,associate's degree,free/reduced,none,64,73,68,256
257,male,group C,associate's degree,standard,completed,78,77,77,257
258,female,group B,some college,standard,none,70,75,78,258
259,female,group C,master's degree,free/reduced,completed,65,81,81,259
260,female,group C,some high school,free/reduced,completed,64,79,77,260
261,male,group C,some college,standard,completed,79,79,78,261
262,female,group C,some high school,free/reduced,none,44,50,51,262
263,female,group E,high school,standard,none,99,93,90,263
264,male,group D,high school,standard,none,76,73,68,264
265,male,group D,some high school,free/reduced,none,59,42,41,265
266,female,group C,bachelor's degree,standard,none,63,75,81,266
267,female,group D,high school,standard,none,69,72,77,267
268,female,group D,associate's degree,standard,completed,88,92,95,268
269,female,group E,some college,free/reduced,none,71,76,70,269
270,male,group C,bachelor's degree,standard,none,69,63,61,270
271,male,group C,some college,standard,none,58,49,42,271
272,female,group D,associate's degree,free/reduced,none,47,53,58,272
273,female,group D,some college,standard,none,65,70,71,273
274,male,group B,some college,standard,completed,88,85,76,274
275,male,group C,bachelor's degree,standard,none,83,78,73,275
276,female,group C,some high school,standard,completed,85,92,93,276
277,female,group E,high school,standard,completed,59,63,75,277
278,female,group C,some high school,free/reduced,none,65,86,80,278
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,279
280,male,group D,high school,standard,none,53,52,42,280
281,male,group D,high school,standard,none,45,48,46,281
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,282
283,female,group D,some college,free/reduced,completed,70,78,78,283
284,female,group B,some high school,standard,none,37,46,46,284
285,male,group B,associate's degree,standard,completed,81,82,82,285
286,male,group E,associate's degree,standard,completed,97,82,88,286
287,female,group B,some high school,standard,none,67,89,82,287
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,288
289,male,group E,some high school,standard,completed,77,76,77,289
290,male,group C,associate's degree,standard,none,76,70,68,290
291,male,group D,some high school,standard,none,86,73,70,291
292,male,group C,some high school,standard,completed,63,60,57,292
293,female,group E,bachelor's degree,standard,none,65,73,75,293
294,male,group D,high school,free/reduced,completed,78,77,80,294
295,male,group B,associate's degree,free/reduced,none,67,62,60,295
296,male,group A,some high school,standard,completed,46,41,43,296
297,male,group E,associate's degree,standard,completed,71,74,68,297
298,male,group C,high school,free/reduced,completed,40,46,50,298
299,male,group D,associate's degree,free/reduced,none,90,87,75,299
300,male,group A,some college,free/reduced,completed,81,78,81,300
301,male,group D,some high school,free/reduced,none,56,54,52,301
302,female,group C,associate's degree,standard,completed,67,84,81,302
303,male,group B,associate's degree,standard,none,80,76,64,303
304,female,group C,associate's degree,standard,completed,74,75,83,304
305,male,group A,some college,standard,none,69,67,69,305
306,male,group E,some college,standard,completed,99,87,81,306
307,male,group C,some high school,standard,none,51,52,44,307
308,female,group B,associate's degree,free/reduced,none,53,71,67,308
309,female,group D,high school,free/reduced,none,49,57,52,309
310,female,group B,associate's degree,standard,none,73,76,80,310
311,male,group B,bachelor's degree,standard,none,66,60,57,311
312,male,group D,bachelor's degree,standard,completed,67,61,68,312

In [49]:
init_language_score=np.random.randint(1,100,size=1000)

In [50]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
5,female,group B,associate's degree,standard,none,71,83,78,5
6,female,group B,some college,standard,completed,88,95,92,6
7,male,group B,some college,free/reduced,none,40,43,39,7
8,male,group D,high school,free/reduced,completed,64,64,67,8
9,female,group B,high school,free/reduced,none,38,60,50,9
10,male,group C,associate's degree,standard,none,58,54,52,10
11,male,group D,associate's degree,standard,none,40,52,43,11
12,female,group B,high school,standard,none,65,81,73,12
13,male,group A,some college,standard,completed,78,72,70,13
14,female,group A,master's degree,standard,none,50,53,58,14
15,female,group C,some high school,standard,none,69,75,78,15
16,male,group C,high school,standard,none,88,89,86,16
17,female,group B,some high school,free/reduced,none,18,32,28,17
18,male,group C,master's degree,free/reduced,completed,46,42,46,18
19,female,group C,associate's degree,free/reduced,none,54,58,61,19
20,male,group D,high school,standard,none,66,69,63,20
21,female,group B,some college,free/reduced,completed,65,75,70,21
22,male,group D,some college,standard,none,44,54,53,22
23,female,group C,some high school,standard,none,69,73,73,23
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,24
25,male,group A,master's degree,free/reduced,none,73,74,72,25
26,male,group B,some college,standard,none,69,54,55,26
27,female,group C,bachelor's degree,standard,none,67,69,75,27
28,male,group C,high school,standard,none,70,70,65,28
29,female,group D,master's degree,standard,none,62,70,75,29
30,female,group D,some college,standard,none,69,74,74,30
31,female,group B,some college,standard,none,63,65,61,31
32,female,group E,master's degree,free/reduced,none,56,72,65,32
33,male,group D,some college,standard,none,40,42,38,33
34,male,group E,some college,standard,none,97,87,82,34
35,male,group E,associate's degree,standard,completed,81,81,79,35
36,female,group D,associate's degree,standard,none,74,81,83,36
37,female,group D,some high school,free/reduced,none,50,64,59,37
38,female,group D,associate's degree,free/reduced,completed,75,90,88,38
39,male,group B,associate's degree,free/reduced,none,57,56,57,39
40,male,group C,associate's degree,free/reduced,none,55,61,54,40
41,female,group C,associate's degree,standard,none,58,73,68,41
42,female,group B,associate's degree,standard,none,53,58,65,42
43,male,group B,some college,free/reduced,completed,59,65,66,43
44,female,group E,associate's degree,free/reduced,none,50,56,54,44
45,male,group B,associate's degree,standard,none,65,54,57,45
46,female,group A,associate's degree,standard,completed,55,65,62,46
47,female,group C,high school,standard,none,66,71,76,47
48,female,group D,associate's degree,free/reduced,completed,57,74,76,48
49,male,group C,high school,standard,completed,82,84,82,49
50,male,group E,some college,standard,none,53,55,48,50
51,male,group E,associate's degree,free/reduced,completed,77,69,68,51
52,male,group C,some college,standard,none,53,44,42,52
53,male,group D,high school,standard,none,88,78,75,53
54,female,group C,some high school,free/reduced,completed,71,84,87,54
55,female,group C,high school,free/reduced,none,33,41,43,55
56,female,group E,associate's degree,standard,completed,82,85,86,56
57,male,group D,associate's degree,standard,none,52,55,49,57
58,male,group D,some college,standard,completed,58,59,58,58
59,female,group C,some high school,free/reduced,none,0,17,10,59
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,60
61,male,group A,some high school,free/reduced,none,39,39,34,61
62,male,group A,associate's degree,free/reduced,none,62,61,55,62
63,female,group C,associate's degree,standard,none,69,80,71,63
64,female,group D,some high school,standard,none,59,58,59,64
65,male,group B,some high school,standard,none,67,64,61,65
66,male,group D,some high school,free/reduced,none,45,37,37,66
67,female,group C,some college,standard,none,60,72,74,67
68,male,group B,associate's degree,free/reduced,none,61,58,56,68
69,female,group C,associate's degree,standard,none,39,64,57,69
70,female,group D,some college,free/reduced,completed,58,63,73,70
71,male,group D,some college,standard,completed,63,55,63,71
72,female,group A,associate's degree,free/reduced,none,41,51,48,72
73,male,group C,some high school,free/reduced,none,61,57,56,73
74,male,group C,some high school,standard,none,49,49,41,74
75,male,group B,associate's degree,free/reduced,none,44,41,38,75
76,male,group E,some high school,standard,none,30,26,22,76
77,male,group A,bachelor's degree,standard,completed,80,78,81,77
78,female,group D,some high school,standard,completed,61,74,72,78
79,female,group E,master's degree,standard,none,62,68,68,79
80,female,group B,associate's degree,standard,none,47,49,50,80
81,male,group B,high school,free/reduced,none,49,45,45,81
82,male,group A,some college,free/reduced,completed,50,47,54,82
83,male,group E,associate's degree,standard,none,72,64,63,83
84,male,group D,high school,free/reduced,none,42,39,34,84
85,female,group C,some college,standard,none,73,80,82,85
86,female,group C,some college,free/reduced,none,76,83,88,86
87,female,group D,associate's degree,standard,none,71,71,74,87
88,female,group A,some college,standard,none,58,70,67,88
89,female,group D,some high school,standard,none,73,86,82,89
90,female,group C,bachelor's degree,standard,none,65,72,74,90
91,male,group C,high school,free/reduced,none,27,34,36,91
92,male,group C,high school,standard,none,71,79,71,92
93,male,group C,associate's degree,free/reduced,completed,43,45,50,93
94,female,group B,some college,standard,none,79,86,92,94
95,male,group C,associate's degree,free/reduced,completed,78,81,82,95
96,male,group B,some high school,standard,completed,65,66,62,96
97,female,group E,some college,standard,completed,63,72,70,97
98,female,group D,some college,free/reduced,none,58,67,62,98
99,female,group D,bachelor's degree,standard,none,65,67,62,99
100,male,group B,some college,standard,none,79,67,67,100
101,male,group D,bachelor's degree,standard,completed,68,74,74,101
102,female,group D,associate's degree,standard,none,85,91,89,102
103,male,group B,high school,standard,completed,60,44,47,103
104,male,group C,some college,standard,completed,98,86,90,104
105,female,group C,some college,standard,none,58,67,72,105
106,female,group D,master's degree,standard,none,87,100,100,106
107,male,group E,associate's degree,standard,completed,66,63,64,107
108,female,group B,associate's degree,free/reduced,none,52,76,70,108
109,female,group B,some high school,standard,none,70,64,72,109
110,female,group D,associate's degree,free/reduced,completed,77,89,98,110
111,male,group C,high school,standard,none,62,55,49,111
112,male,group A,associate's degree,standard,none,54,53,47,112
113,female,group D,some college,standard,none,51,58,54,113
114,female,group E,bachelor's degree,standard,completed,99,100,100,114
115,male,group C,high school,standard,none,84,77,74,115
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,116
117,female,group D,bachelor's degree,standard,none,78,82,79,117
118,female,group D,some high school,standard,none,51,63,61,118
119,female,group C,some college,standard,none,55,69,65,119
120,female,group C,bachelor's degree,standard,completed,79,92,89,120
121,male,group B,associate's degree,standard,completed,91,89,92,121
122,female,group C,some college,standard,completed,88,93,93,122
123,male,group D,high school,free/reduced,none,63,57,56,123
124,male,group E,some college,standard,none,83,80,73,124
125,female,group B,high school,standard,none,87,95,86,125
126,male,group B,some high school,standard,none,72,68,67,126
127,male,group D,some college,standard,completed,65,77,74,127
128,male,group D,master's degree,standard,none,82,82,74,128
129,female,group A,bachelor's degree,standard,none,51,49,51,129
130,male,group D,master's degree,standard,none,89,84,82,130
131,male,group C,some high school,free/reduced,completed,53,37,40,131
132,male,group E,some college,free/reduced,completed,87,74,70,132
133,female,group C,some college,standard,completed,75,81,84,133
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,134
135,male,group C,bachelor's degree,standard,none,58,55,48,135
136,male,group B,some high school,standard,completed,51,54,41,136
137,male,group E,high school,standard,none,70,55,56,137
138,female,group C,associate's degree,standard,none,59,66,67,138
139,male,group D,some college,standard,completed,71,61,69,139
140,female,group D,some high school,standard,none,76,72,71,140
141,female,group C,some college,free/reduced,none,59,62,64,141
142,female,group E,some college,free/reduced,completed,42,55,54,142
143,male,group A,high school,standard,none,57,43,47,143
144,male,group D,some college,standard,none,88,73,78,144
145,female,group C,some college,free/reduced,none,22,39,33,145
146,male,group B,some high school,standard,none,88,84,75,146
147,male,group C,associate's degree,free/reduced,none,73,68,66,147
148,female,group D,bachelor's degree,standard,completed,68,75,81,148
149,male,group E,associate's degree,free/reduced,completed,100,100,93,149
150,male,group A,some high school,standard,completed,62,67,69,150
151,male,group A,bachelor's degree,standard,none,77,67,68,151
152,female,group B,associate's degree,standard,completed,59,70,66,152
153,male,group D,bachelor's degree,standard,none,54,49,47,153
154,male,group D,some high school,standard,none,62,67,61,154
155,female,group C,some college,standard,completed,70,89,88,155
156,female,group E,high school,free/reduced,completed,66,74,78,156
157,male,group B,some college,free/reduced,none,60,60,60,157
158,female,group B,associate's degree,standard,completed,61,86,87,158
159,male,group D,associate's degree,free/reduced,none,66,62,64,159
160,male,group B,associate's degree,free/reduced,completed,82,78,74,160
161,female,group E,some college,free/reduced,completed,75,88,85,161
162,male,group B,master's degree,free/reduced,none,49,53,52,162
163,male,group C,high school,standard,none,52,53,49,163
164,female,group E,master's degree,standard,none,81,92,91,164
165,female,group C,bachelor's degree,standard,completed,96,100,100,165
166,male,group C,high school,free/reduced,completed,53,51,51,166
167,female,group B,master's degree,free/reduced,completed,58,76,78,167
168,female,group B,high school,standard,completed,68,83,78,168
169,female,group C,some college,free/reduced,completed,67,75,70,169
170,male,group A,high school,standard,completed,72,73,74,170
171,male,group E,some high school,standard,none,94,88,78,171
172,female,group D,some college,standard,none,79,86,81,172
173,female,group C,associate's degree,standard,none,63,67,70,173
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,174
175,female,group C,master's degree,standard,completed,81,91,87,175
176,female,group B,high school,free/reduced,completed,46,54,58,176
177,female,group C,associate's degree,standard,completed,71,77,77,177
178,female,group B,master's degree,free/reduced,completed,52,70,62,178
179,female,group D,some high school,standard,completed,97,100,100,179
180,male,group C,master's degree,free/reduced,completed,62,68,75,180
181,female,group C,some college,free/reduced,none,46,64,66,181
182,female,group E,high school,standard,none,50,50,47,182
183,female,group D,associate's degree,standard,none,65,69,70,183
184,male,group C,some high school,free/reduced,completed,45,52,49,184
185,male,group C,associate's degree,free/reduced,completed,65,67,65,185
186,male,group E,high school,standard,none,80,76,65,186
187,male,group D,some high school,standard,completed,62,66,68,187
188,male,group B,some high school,free/reduced,none,48,52,45,188
189,female,group C,bachelor's degree,standard,none,77,88,87,189
190,female,group E,associate's degree,standard,none,66,65,69,190
191,male,group D,some college,standard,completed,76,83,79,191
192,female,group B,some high school,standard,none,62,64,66,192
193,male,group D,some college,standard,completed,77,62,62,193
194,female,group C,master's degree,standard,completed,69,84,85,194
195,male,group D,associate's degree,standard,none,61,55,52,195
196,male,group C,some high school,free/reduced,completed,59,69,65,196
197,male,group E,high school,free/reduced,none,55,56,51,197
198,female,group B,some college,free/reduced,none,45,53,55,198
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,199
200,female,group C,associate's degree,standard,completed,67,84,86,200
201,female,group D,some college,free/reduced,none,65,81,77,201
202,male,group C,associate's degree,standard,none,69,77,69,202
203,female,group B,associate's degree,standard,none,57,69,68,203
204,male,group C,some college,standard,none,59,41,42,204
205,male,group D,some high school,standard,completed,74,71,78,205
206,male,group E,bachelor's degree,standard,none,82,62,62,206
207,male,group E,high school,standard,completed,81,80,76,207
208,female,group B,some college,free/reduced,none,74,81,76,208
209,female,group B,some college,free/reduced,none,58,61,66,209
210,male,group D,some high school,free/reduced,completed,80,79,79,210
211,male,group C,some college,free/reduced,none,35,28,27,211
212,female,group C,high school,free/reduced,none,42,62,60,212
213,male,group C,associate's degree,free/reduced,completed,60,51,56,213
214,male,group E,high school,standard,completed,87,91,81,214
215,male,group B,some high school,standard,completed,84,83,75,215
216,female,group E,associate's degree,free/reduced,completed,83,86,88,216
217,female,group C,high school,free/reduced,none,34,42,39,217
218,male,group B,high school,free/reduced,none,66,77,70,218
219,male,group B,some high school,standard,completed,61,56,56,219
220,female,group D,high school,standard,completed,56,68,74,220
221,male,group B,associate's degree,standard,none,87,85,73,221
222,female,group C,some high school,free/reduced,none,55,65,62,222
223,male,group D,some high school,standard,none,86,80,75,223
224,female,group B,associate's degree,standard,completed,52,66,73,224
225,female,group E,master's degree,free/reduced,none,45,56,54,225
226,female,group C,some college,standard,none,72,72,71,226
227,male,group D,high school,standard,none,57,50,54,227
228,male,group A,some high school,free/reduced,none,68,72,64,228
229,female,group C,some college,standard,completed,88,95,94,229
230,male,group D,some college,standard,none,76,64,66,230
231,male,group C,associate's degree,standard,none,46,43,42,231
232,female,group B,bachelor's degree,standard,none,67,86,83,232
233,male,group E,some high school,standard,none,92,87,78,233
234,male,group C,bachelor's degree,standard,completed,83,82,84,234
235,male,group D,associate's degree,standard,none,80,75,77,235
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,236
237,female,group D,some high school,standard,completed,64,60,74,237
238,male,group B,some college,standard,none,54,52,51,238
239,male,group C,associate's degree,standard,none,84,80,80,239
240,male,group D,high school,free/reduced,completed,73,68,66,240
241,female,group E,bachelor's degree,standard,none,80,83,83,241
242,female,group D,high school,standard,none,56,52,55,242
243,male,group E,some college,standard,none,59,51,43,243
244,male,group D,some high school,standard,none,75,74,69,244
245,male,group C,associate's degree,standard,none,85,76,71,245
246,male,group E,associate's degree,standard,none,89,76,74,246
247,female,group B,high school,standard,completed,58,70,68,247
248,female,group B,high school,standard,none,65,64,62,248
249,male,group C,high school,standard,none,68,60,53,249
250,male,group A,some high school,standard,completed,47,49,49,250
251,female,group D,some college,free/reduced,none,71,83,83,251
252,female,group B,some high school,standard,completed,60,70,70,252
253,male,group D,master's degree,standard,none,80,80,72,253
254,male,group D,high school,standard,none,54,52,52,254
255,female,group E,some college,standard,none,62,73,70,255
256,female,group C,associate's degree,free/reduced,none,64,73,68,256
257,male,group C,associate's degree,standard,completed,78,77,77,257
258,female,group B,some college,standard,none,70,75,78,258
259,female,group C,master's degree,free/reduced,completed,65,81,81,259
260,female,group C,some high school,free/reduced,completed,64,79,77,260
261,male,group C,some college,standard,completed,79,79,78,261
262,female,group C,some high school,free/reduced,none,44,50,51,262
263,female,group E,high school,standard,none,99,93,90,263
264,male,group D,high school,standard,none,76,73,68,264
265,male,group D,some high school,free/reduced,none,59,42,41,265
266,female,group C,bachelor's degree,standard,none,63,75,81,266
267,female,group D,high school,standard,none,69,72,77,267
268,female,group D,associate's degree,standard,completed,88,92,95,268
269,female,group E,some college,free/reduced,none,71,76,70,269
270,male,group C,bachelor's degree,standard,none,69,63,61,270
271,male,group C,some college,standard,none,58,49,42,271
272,female,group D,associate's degree,free/reduced,none,47,53,58,272
273,female,group D,some college,standard,none,65,70,71,273
274,male,group B,some college,standard,completed,88,85,76,274
275,male,group C,bachelor's degree,standard,none,83,78,73,275
276,female,group C,some high school,standard,completed,85,92,93,276
277,female,group E,high school,standard,completed,59,63,75,277
278,female,group C,some high school,free/reduced,none,65,86,80,278
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,279
280,male,group D,high school,standard,none,53,52,42,280
281,male,group D,high school,standard,none,45,48,46,281
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,282
283,female,group D,some college,free/reduced,completed,70,78,78,283
284,female,group B,some high school,standard,none,37,46,46,284
285,male,group B,associate's degree,standard,completed,81,82,82,285
286,male,group E,associate's degree,standard,completed,97,82,88,286
287,female,group B,some high school,standard,none,67,89,82,287
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,288
289,male,group E,some high school,standard,completed,77,76,77,289
290,male,group C,associate's degree,standard,none,76,70,68,290
291,male,group D,some high school,standard,none,86,73,70,291
292,male,group C,some high school,standard,completed,63,60,57,292
293,female,group E,bachelor's degree,standard,none,65,73,75,293
294,male,group D,high school,free/reduced,completed,78,77,80,294
295,male,group B,associate's degree,free/reduced,none,67,62,60,295
296,male,group A,some high school,standard,completed,46,41,43,296
297,male,group E,associate's degree,standard,completed,71,74,68,297
298,male,group C,high school,free/reduced,completed,40,46,50,298
299,male,group D,associate's degree,free/reduced,none,90,87,75,299
300,male,group A,some college,free/reduced,completed,81,78,81,300
301,male,group D,some high school,free/reduced,none,56,54,52,301
302,female,group C,associate's degree,standard,completed,67,84,81,302
303,male,group B,associate's degree,standard,none,80,76,64,303
304,female,group C,associate's degree,standard,completed,74,75,83,304
305,male,group A,some college,standard,none,69,67,69,305
306,male,group E,some college,standard,completed,99,87,81,306
307,male,group C,some high school,standard,none,51,52,44,307
308,female,group B,associate's degree,free/reduced,none,53,71,67,308
309,female,group D,high school,free/reduced,none,49,57,52,309
310,female,group B,associate's degree,standard,none,73,76,80,310
311,male,group B,bachelor's degree,standard,none,66,60,57,311
312,male,group D,bachelor's degree,standard,completed,67,61,68,312

In [56]:
df['language score']=init_language_score

In [53]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,34
1,female,group C,some college,standard,completed,69,90,88,17
2,female,group B,master's degree,standard,none,90,95,93,75
3,male,group A,associate's degree,free/reduced,none,47,57,44,43
4,male,group C,some college,standard,none,76,78,75,42
5,female,group B,associate's degree,standard,none,71,83,78,95
6,female,group B,some college,standard,completed,88,95,92,37
7,male,group B,some college,free/reduced,none,40,43,39,13
8,male,group D,high school,free/reduced,completed,64,64,67,68
9,female,group B,high school,free/reduced,none,38,60,50,56
10,male,group C,associate's degree,standard,none,58,54,52,62
11,male,group D,associate's degree,standard,none,40,52,43,5
12,female,group B,high school,standard,none,65,81,73,40
13,male,group A,some college,standard,completed,78,72,70,40
14,female,group A,master's degree,standard,none,50,53,58,22
15,female,group C,some high school,standard,none,69,75,78,31
16,male,group C,high school,standard,none,88,89,86,53
17,female,group B,some high school,free/reduced,none,18,32,28,12
18,male,group C,master's degree,free/reduced,completed,46,42,46,8
19,female,group C,associate's degree,free/reduced,none,54,58,61,55
20,male,group D,high school,standard,none,66,69,63,16
21,female,group B,some college,free/reduced,completed,65,75,70,92
22,male,group D,some college,standard,none,44,54,53,90
23,female,group C,some high school,standard,none,69,73,73,96
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,60
25,male,group A,master's degree,free/reduced,none,73,74,72,99
26,male,group B,some college,standard,none,69,54,55,40
27,female,group C,bachelor's degree,standard,none,67,69,75,56
28,male,group C,high school,standard,none,70,70,65,29
29,female,group D,master's degree,standard,none,62,70,75,28
30,female,group D,some college,standard,none,69,74,74,75
31,female,group B,some college,standard,none,63,65,61,48
32,female,group E,master's degree,free/reduced,none,56,72,65,23
33,male,group D,some college,standard,none,40,42,38,32
34,male,group E,some college,standard,none,97,87,82,93
35,male,group E,associate's degree,standard,completed,81,81,79,46
36,female,group D,associate's degree,standard,none,74,81,83,50
37,female,group D,some high school,free/reduced,none,50,64,59,65
38,female,group D,associate's degree,free/reduced,completed,75,90,88,28
39,male,group B,associate's degree,free/reduced,none,57,56,57,39
40,male,group C,associate's degree,free/reduced,none,55,61,54,16
41,female,group C,associate's degree,standard,none,58,73,68,3
42,female,group B,associate's degree,standard,none,53,58,65,68
43,male,group B,some college,free/reduced,completed,59,65,66,62
44,female,group E,associate's degree,free/reduced,none,50,56,54,71
45,male,group B,associate's degree,standard,none,65,54,57,48
46,female,group A,associate's degree,standard,completed,55,65,62,70
47,female,group C,high school,standard,none,66,71,76,9
48,female,group D,associate's degree,free/reduced,completed,57,74,76,5
49,male,group C,high school,standard,completed,82,84,82,4
50,male,group E,some college,standard,none,53,55,48,58
51,male,group E,associate's degree,free/reduced,completed,77,69,68,75
52,male,group C,some college,standard,none,53,44,42,42
53,male,group D,high school,standard,none,88,78,75,90
54,female,group C,some high school,free/reduced,completed,71,84,87,91
55,female,group C,high school,free/reduced,none,33,41,43,64
56,female,group E,associate's degree,standard,completed,82,85,86,18
57,male,group D,associate's degree,standard,none,52,55,49,3
58,male,group D,some college,standard,completed,58,59,58,17
59,female,group C,some high school,free/reduced,none,0,17,10,59
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,40
61,male,group A,some high school,free/reduced,none,39,39,34,87
62,male,group A,associate's degree,free/reduced,none,62,61,55,50
63,female,group C,associate's degree,standard,none,69,80,71,42
64,female,group D,some high school,standard,none,59,58,59,28
65,male,group B,some high school,standard,none,67,64,61,96
66,male,group D,some high school,free/reduced,none,45,37,37,90
67,female,group C,some college,standard,none,60,72,74,45
68,male,group B,associate's degree,free/reduced,none,61,58,56,24
69,female,group C,associate's degree,standard,none,39,64,57,18
70,female,group D,some college,free/reduced,completed,58,63,73,63
71,male,group D,some college,standard,completed,63,55,63,72
72,female,group A,associate's degree,free/reduced,none,41,51,48,51
73,male,group C,some high school,free/reduced,none,61,57,56,11
74,male,group C,some high school,standard,none,49,49,41,41
75,male,group B,associate's degree,free/reduced,none,44,41,38,87
76,male,group E,some high school,standard,none,30,26,22,92
77,male,group A,bachelor's degree,standard,completed,80,78,81,31
78,female,group D,some high school,standard,completed,61,74,72,85
79,female,group E,master's degree,standard,none,62,68,68,77
80,female,group B,associate's degree,standard,none,47,49,50,18
81,male,group B,high school,free/reduced,none,49,45,45,80
82,male,group A,some college,free/reduced,completed,50,47,54,52
83,male,group E,associate's degree,standard,none,72,64,63,89
84,male,group D,high school,free/reduced,none,42,39,34,74
85,female,group C,some college,standard,none,73,80,82,20
86,female,group C,some college,free/reduced,none,76,83,88,12
87,female,group D,associate's degree,standard,none,71,71,74,92
88,female,group A,some college,standard,none,58,70,67,47
89,female,group D,some high school,standard,none,73,86,82,1
90,female,group C,bachelor's degree,standard,none,65,72,74,73
91,male,group C,high school,free/reduced,none,27,34,36,7
92,male,group C,high school,standard,none,71,79,71,53
93,male,group C,associate's degree,free/reduced,completed,43,45,50,71
94,female,group B,some college,standard,none,79,86,92,68
95,male,group C,associate's degree,free/reduced,completed,78,81,82,2
96,male,group B,some high school,standard,completed,65,66,62,82
97,female,group E,some college,standard,completed,63,72,70,75
98,female,group D,some college,free/reduced,none,58,67,62,83
99,female,group D,bachelor's degree,standard,none,65,67,62,43
100,male,group B,some college,standard,none,79,67,67,86
101,male,group D,bachelor's degree,standard,completed,68,74,74,35
102,female,group D,associate's degree,standard,none,85,91,89,36
103,male,group B,high school,standard,completed,60,44,47,86
104,male,group C,some college,standard,completed,98,86,90,53
105,female,group C,some college,standard,none,58,67,72,74
106,female,group D,master's degree,standard,none,87,100,100,37
107,male,group E,associate's degree,standard,completed,66,63,64,40
108,female,group B,associate's degree,free/reduced,none,52,76,70,55
109,female,group B,some high school,standard,none,70,64,72,91
110,female,group D,associate's degree,free/reduced,completed,77,89,98,24
111,male,group C,high school,standard,none,62,55,49,1
112,male,group A,associate's degree,standard,none,54,53,47,76
113,female,group D,some college,standard,none,51,58,54,55
114,female,group E,bachelor's degree,standard,completed,99,100,100,74
115,male,group C,high school,standard,none,84,77,74,21
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,73
117,female,group D,bachelor's degree,standard,none,78,82,79,12
118,female,group D,some high school,standard,none,51,63,61,55
119,female,group C,some college,standard,none,55,69,65,27
120,female,group C,bachelor's degree,standard,completed,79,92,89,5
121,male,group B,associate's degree,standard,completed,91,89,92,11
122,female,group C,some college,standard,completed,88,93,93,84
123,male,group D,high school,free/reduced,none,63,57,56,88
124,male,group E,some college,standard,none,83,80,73,44
125,female,group B,high school,standard,none,87,95,86,10
126,male,group B,some high school,standard,none,72,68,67,55
127,male,group D,some college,standard,completed,65,77,74,32
128,male,group D,master's degree,standard,none,82,82,74,66
129,female,group A,bachelor's degree,standard,none,51,49,51,94
130,male,group D,master's degree,standard,none,89,84,82,19
131,male,group C,some high school,free/reduced,completed,53,37,40,59
132,male,group E,some college,free/reduced,completed,87,74,70,44
133,female,group C,some college,standard,completed,75,81,84,37
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,97
135,male,group C,bachelor's degree,standard,none,58,55,48,13
136,male,group B,some high school,standard,completed,51,54,41,6
137,male,group E,high school,standard,none,70,55,56,67
138,female,group C,associate's degree,standard,none,59,66,67,62
139,male,group D,some college,standard,completed,71,61,69,85
140,female,group D,some high school,standard,none,76,72,71,60
141,female,group C,some college,free/reduced,none,59,62,64,66
142,female,group E,some college,free/reduced,completed,42,55,54,63
143,male,group A,high school,standard,none,57,43,47,53
144,male,group D,some college,standard,none,88,73,78,91
145,female,group C,some college,free/reduced,none,22,39,33,42
146,male,group B,some high school,standard,none,88,84,75,94
147,male,group C,associate's degree,free/reduced,none,73,68,66,89
148,female,group D,bachelor's degree,standard,completed,68,75,81,29
149,male,group E,associate's degree,free/reduced,completed,100,100,93,4
150,male,group A,some high school,standard,completed,62,67,69,59
151,male,group A,bachelor's degree,standard,none,77,67,68,18
152,female,group B,associate's degree,standard,completed,59,70,66,41
153,male,group D,bachelor's degree,standard,none,54,49,47,32
154,male,group D,some high school,standard,none,62,67,61,64
155,female,group C,some college,standard,completed,70,89,88,14
156,female,group E,high school,free/reduced,completed,66,74,78,91
157,male,group B,some college,free/reduced,none,60,60,60,90
158,female,group B,associate's degree,standard,completed,61,86,87,9
159,male,group D,associate's degree,free/reduced,none,66,62,64,28
160,male,group B,associate's degree,free/reduced,completed,82,78,74,74
161,female,group E,some college,free/reduced,completed,75,88,85,61
162,male,group B,master's degree,free/reduced,none,49,53,52,67
163,male,group C,high school,standard,none,52,53,49,54
164,female,group E,master's degree,standard,none,81,92,91,66
165,female,group C,bachelor's degree,standard,completed,96,100,100,82
166,male,group C,high school,free/reduced,completed,53,51,51,57
167,female,group B,master's degree,free/reduced,completed,58,76,78,18
168,female,group B,high school,standard,completed,68,83,78,7
169,female,group C,some college,free/reduced,completed,67,75,70,45
170,male,group A,high school,standard,completed,72,73,74,69
171,male,group E,some high school,standard,none,94,88,78,22
172,female,group D,some college,standard,none,79,86,81,52
173,female,group C,associate's degree,standard,none,63,67,70,2
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,84
175,female,group C,master's degree,standard,completed,81,91,87,64
176,female,group B,high school,free/reduced,completed,46,54,58,80
177,female,group C,associate's degree,standard,completed,71,77,77,68
178,female,group B,master's degree,free/reduced,completed,52,70,62,41
179,female,group D,some high school,standard,completed,97,100,100,76
180,male,group C,master's degree,free/reduced,completed,62,68,75,15
181,female,group C,some college,free/reduced,none,46,64,66,8
182,female,group E,high school,standard,none,50,50,47,35
183,female,group D,associate's degree,standard,none,65,69,70,43
184,male,group C,some high school,free/reduced,completed,45,52,49,59
185,male,group C,associate's degree,free/reduced,completed,65,67,65,30
186,male,group E,high school,standard,none,80,76,65,25
187,male,group D,some high school,standard,completed,62,66,68,20
188,male,group B,some high school,free/reduced,none,48,52,45,17
189,female,group C,bachelor's degree,standard,none,77,88,87,27
190,female,group E,associate's degree,standard,none,66,65,69,79
191,male,group D,some college,standard,completed,76,83,79,5
192,female,group B,some high school,standard,none,62,64,66,17
193,male,group D,some college,standard,completed,77,62,62,40
194,female,group C,master's degree,standard,completed,69,84,85,42
195,male,group D,associate's degree,standard,none,61,55,52,97
196,male,group C,some high school,free/reduced,completed,59,69,65,48
197,male,group E,high school,free/reduced,none,55,56,51,15
198,female,group B,some college,free/reduced,none,45,53,55,97
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,20
200,female,group C,associate's degree,standard,completed,67,84,86,1
201,female,group D,some college,free/reduced,none,65,81,77,10
202,male,group C,associate's degree,standard,none,69,77,69,47
203,female,group B,associate's degree,standard,none,57,69,68,19
204,male,group C,some college,standard,none,59,41,42,90
205,male,group D,some high school,standard,completed,74,71,78,52
206,male,group E,bachelor's degree,standard,none,82,62,62,40
207,male,group E,high school,standard,completed,81,80,76,26
208,female,group B,some college,free/reduced,none,74,81,76,64
209,female,group B,some college,free/reduced,none,58,61,66,96
210,male,group D,some high school,free/reduced,completed,80,79,79,84
211,male,group C,some college,free/reduced,none,35,28,27,67
212,female,group C,high school,free/reduced,none,42,62,60,1
213,male,group C,associate's degree,free/reduced,completed,60,51,56,49
214,male,group E,high school,standard,completed,87,91,81,62
215,male,group B,some high school,standard,completed,84,83,75,44
216,female,group E,associate's degree,free/reduced,completed,83,86,88,45
217,female,group C,high school,free/reduced,none,34,42,39,43
218,male,group B,high school,free/reduced,none,66,77,70,25
219,male,group B,some high school,standard,completed,61,56,56,15
220,female,group D,high school,standard,completed,56,68,74,3
221,male,group B,associate's degree,standard,none,87,85,73,30
222,female,group C,some high school,free/reduced,none,55,65,62,51
223,male,group D,some high school,standard,none,86,80,75,86
224,female,group B,associate's degree,standard,completed,52,66,73,56
225,female,group E,master's degree,free/reduced,none,45,56,54,26
226,female,group C,some college,standard,none,72,72,71,83
227,male,group D,high school,standard,none,57,50,54,67
228,male,group A,some high school,free/reduced,none,68,72,64,5
229,female,group C,some college,standard,completed,88,95,94,81
230,male,group D,some college,standard,none,76,64,66,73
231,male,group C,associate's degree,standard,none,46,43,42,6
232,female,group B,bachelor's degree,standard,none,67,86,83,32
233,male,group E,some high school,standard,none,92,87,78,27
234,male,group C,bachelor's degree,standard,completed,83,82,84,53
235,male,group D,associate's degree,standard,none,80,75,77,25
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,35
237,female,group D,some high school,standard,completed,64,60,74,28
238,male,group B,some college,standard,none,54,52,51,36
239,male,group C,associate's degree,standard,none,84,80,80,24
240,male,group D,high school,free/reduced,completed,73,68,66,53
241,female,group E,bachelor's degree,standard,none,80,83,83,22
242,female,group D,high school,standard,none,56,52,55,33
243,male,group E,some college,standard,none,59,51,43,73
244,male,group D,some high school,standard,none,75,74,69,11
245,male,group C,associate's degree,standard,none,85,76,71,43
246,male,group E,associate's degree,standard,none,89,76,74,39
247,female,group B,high school,standard,completed,58,70,68,42
248,female,group B,high school,standard,none,65,64,62,81
249,male,group C,high school,standard,none,68,60,53,72
250,male,group A,some high school,standard,completed,47,49,49,39
251,female,group D,some college,free/reduced,none,71,83,83,14
252,female,group B,some high school,standard,completed,60,70,70,79
253,male,group D,master's degree,standard,none,80,80,72,18
254,male,group D,high school,standard,none,54,52,52,16
255,female,group E,some college,standard,none,62,73,70,44
256,female,group C,associate's degree,free/reduced,none,64,73,68,60
257,male,group C,associate's degree,standard,completed,78,77,77,26
258,female,group B,some college,standard,none,70,75,78,81
259,female,group C,master's degree,free/reduced,completed,65,81,81,94
260,female,group C,some high school,free/reduced,completed,64,79,77,70
261,male,group C,some college,standard,completed,79,79,78,13
262,female,group C,some high school,free/reduced,none,44,50,51,22
263,female,group E,high school,standard,none,99,93,90,96
264,male,group D,high school,standard,none,76,73,68,46
265,male,group D,some high school,free/reduced,none,59,42,41,8
266,female,group C,bachelor's degree,standard,none,63,75,81,77
267,female,group D,high school,standard,none,69,72,77,28
268,female,group D,associate's degree,standard,completed,88,92,95,89
269,female,group E,some college,free/reduced,none,71,76,70,10
270,male,group C,bachelor's degree,standard,none,69,63,61,53
271,male,group C,some college,standard,none,58,49,42,55
272,female,group D,associate's degree,free/reduced,none,47,53,58,50
273,female,group D,some college,standard,none,65,70,71,28
274,male,group B,some college,standard,completed,88,85,76,75
275,male,group C,bachelor's degree,standard,none,83,78,73,41
276,female,group C,some high school,standard,completed,85,92,93,82
277,female,group E,high school,standard,completed,59,63,75,66
278,female,group C,some high school,free/reduced,none,65,86,80,92
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,96
280,male,group D,high school,standard,none,53,52,42,1
281,male,group D,high school,standard,none,45,48,46,1
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,89
283,female,group D,some college,free/reduced,completed,70,78,78,16
284,female,group B,some high school,standard,none,37,46,46,24
285,male,group B,associate's degree,standard,completed,81,82,82,85
286,male,group E,associate's degree,standard,completed,97,82,88,47
287,female,group B,some high school,standard,none,67,89,82,92
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,92
289,male,group E,some high school,standard,completed,77,76,77,79
290,male,group C,associate's degree,standard,none,76,70,68,93
291,male,group D,some high school,standard,none,86,73,70,42
292,male,group C,some high school,standard,completed,63,60,57,1
293,female,group E,bachelor's degree,standard,none,65,73,75,60
294,male,group D,high school,free/reduced,completed,78,77,80,96
295,male,group B,associate's degree,free/reduced,none,67,62,60,7
296,male,group A,some high school,standard,completed,46,41,43,57
297,male,group E,associate's degree,standard,completed,71,74,68,43
298,male,group C,high school,free/reduced,completed,40,46,50,52
299,male,group D,associate's degree,free/reduced,none,90,87,75,82
300,male,group A,some college,free/reduced,completed,81,78,81,20
301,male,group D,some high school,free/reduced,none,56,54,52,41
302,female,group C,associate's degree,standard,completed,67,84,81,78
303,male,group B,associate's degree,standard,none,80,76,64,79
304,female,group C,associate's degree,standard,completed,74,75,83,40
305,male,group A,some college,standard,none,69,67,69,42
306,male,group E,some college,standard,completed,99,87,81,68
307,male,group C,some high school,standard,none,51,52,44,82
308,female,group B,associate's degree,free/reduced,none,53,71,67,88
309,female,group D,high school,free/reduced,none,49,57,52,28
310,female,group B,associate's degree,standard,none,73,76,80,99
311,male,group B,bachelor's degree,standard,none,66,60,57,52
312,male,group D,bachelor's degree,standard,completed,67,61,68,89
313,female,group C,associate's degree,free/reduced,completed,68,67,69,13
314,female,group C,bachelor's degree,standard,completed,59,64,75,56
315,male,group C,high school,standard,none,71,66,65,86
316,female,group D,master's degree,standard,completed,77,82,91,49