In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

In [ ]:
from google .colab import files

In [ ]:
uploaded=files.upload()

Saving StudentsPerformance.csv to StudentsPerformance (2).csv

In [ ]:
df=pd.read_csv("/content/StudentsPerformance.csv")

In [ ]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [37]:
#CREATE INDEX

In [38]:
import numpy as np
import random

In [41]:
#creating non repetative value for the index
new_index=np.arange(0,1000)
new_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [42]:
#shuffing the index
random.shuffle(new_index)
new_index

array([996, 964, 640, 141, 908, 118, 158, 648, 160, 211, 998, 801, 742,
       457, 887, 567, 769, 520, 917, 589,  61, 109, 565, 698, 680, 270,
        51, 416, 181, 385, 366, 450, 281, 133, 956, 331, 155, 616, 322,
       866, 177, 124, 837, 924, 622, 287, 693, 619, 529, 613,   5, 709,
       170, 668, 243,  98, 422, 925, 631, 384, 289, 843, 271, 393, 781,
       205,  79, 114, 946, 294, 947, 223, 128, 736, 939, 987, 803, 431,
         4, 506, 606, 762, 343, 741, 371, 359, 564, 103, 960, 813, 694,
       797, 533, 588, 214, 948, 702, 577, 363, 430, 895, 988, 743,  23,
        87, 832,  63, 425,  67,  11, 261, 319, 278, 574, 311, 176,  65,
       838, 576, 675,  19, 905, 249, 879, 712, 853, 751, 180, 484, 146,
       608, 645, 791, 820, 961, 346, 911, 134, 228, 869, 435,   2, 706,
       749, 193, 943, 116, 546,  92, 353, 218, 525, 713, 959, 630, 513,
       480, 481, 930, 507, 610, 800, 993, 527, 139, 138, 115, 929, 326,
       338, 357, 358, 404, 247, 999, 112, 424, 581, 724, 470, 209, 402,
       826,  32, 364, 405, 541, 553, 767, 720, 761, 215, 842,  41, 280,
       210, 336, 664, 780, 697, 691, 517, 687, 551, 379, 688, 877, 850,
       909, 532, 474, 105, 787, 977, 411, 183, 744, 658, 689, 373, 627,
       283, 354,  59, 856, 677, 401, 705, 783, 172, 752, 503, 983, 932,
       635, 394, 871, 777, 324, 191, 550, 739, 755, 824, 154, 135, 521,
       602, 443, 255, 318, 560, 502, 831, 633, 750, 634, 396, 334, 583,
       825, 852, 763, 106,  86,  12, 995, 726, 910, 982, 262, 329, 952,
       989, 870, 166, 301, 427, 865, 590, 478, 315, 340, 293,  58, 100,
       727,  81, 636,  57, 447,  88, 152, 674, 536, 980, 950, 968,  50,
       486, 874, 889, 300, 944, 426, 194, 625, 145, 465,  21, 786,  77,
       547, 538, 208,  74, 487, 534, 234, 733, 603, 710, 938, 730, 941,
       259,  13, 789, 846, 231, 291, 526,  44, 467, 284, 754, 651, 445,
       306, 119, 544, 718, 368, 858, 721, 621, 591, 888, 499, 644, 439,
        20, 667, 958, 559, 757, 351, 126, 488, 916, 438, 558, 333, 101,
       505, 915, 279, 760,  38, 302, 981, 266, 169, 808, 414, 339, 195,
       584, 623, 830, 519, 914, 240, 436, 594, 165, 408,  42,  33, 823,
       971, 490,  16,  72, 207, 886, 836, 828, 912, 131, 974, 235, 269,
       738, 920, 901,  53, 936, 821, 365, 310, 543, 665, 382, 844,  28,
       554, 236, 716, 149, 362, 421, 919, 847, 188, 926,  68, 374, 391,
        49, 607, 776, 629, 433, 127, 509, 708, 927, 290, 190, 753, 805,
        82, 229, 561, 732, 966, 578, 994, 876, 222, 437, 355,  10, 448,
       729, 483, 341, 455, 473, 219,   0, 469, 392, 304, 774, 248,  95,
       972, 756, 369, 199, 894, 493, 563, 198, 406, 685,  90, 848, 197,
       758, 121, 136, 159, 985, 372, 220,  96, 419,  17,  36, 684, 849,
        69, 263, 403, 296, 851,  26,  62, 407, 875, 552,  66, 449, 162,
       690, 967, 489, 845, 258, 395, 463, 604, 130, 400, 692, 670, 880,
       973, 601, 935, 835, 468, 904, 570, 891,   9, 485, 244, 841, 890,
       307, 178, 804,  70,  73, 632, 764, 330, 649, 143, 161, 239, 772,
       896,  25, 807, 696, 107,  91, 655, 192, 510, 557, 979, 816, 285,
       579, 620, 770, 792, 241, 976, 531, 701,  52, 399, 676, 678,  48,
       476, 212, 250, 377, 790, 859,  93, 317, 501, 460, 282, 163, 530,
        22, 378, 246,  24, 500, 953, 313, 782, 867, 275, 233, 957, 923,
       965, 641, 323, 918, 238,  39, 907, 216, 794,  83, 232, 596, 174,
       227, 779, 928, 759, 518, 992, 537, 272, 671, 940, 123, 444, 639,
       187, 592, 344, 367, 522, 441, 459, 595, 615, 182, 555, 316, 673,
       265, 656, 122, 861, 984, 386, 327, 893, 148, 350, 299, 264, 628,
       618,  35, 900, 102, 360, 747, 498, 230, 885, 137, 796, 189,  78,
       798, 398, 224, 662, 452, 734, 185, 383,  27, 387, 883, 672, 666,
       572, 461, 260, 937, 954, 704, 375, 111, 637, 700, 934, 626, 827,
       840, 571, 147, 711, 771, 586, 542, 409, 361, 793, 286, 799, 276,
       834,  43, 562, 348, 125, 872, 251, 432, 140, 818, 104, 273, 256,
       320, 472, 202, 725, 873, 650, 768, 120, 535, 922, 609, 497, 903,
         1, 882, 454, 814, 898, 703, 242, 669, 312, 978, 723, 731, 417,
        85, 412, 415, 156, 643, 456, 788, 942, 933, 164, 990, 746, 815,
       740, 854, 878,  99, 795, 504, 168, 305, 423, 810, 277, 913, 434,
        60, 812,  75, 945,  55, 884, 881, 599, 295, 660, 335, 376, 614,
       150, 963, 298,  18, 659, 292, 955, 201, 735, 707, 566, 297, 254,
       863, 892, 714, 495, 817,  56, 113, 681, 167, 575, 748, 428, 949,
       722, 931, 611, 975, 686, 556,  34, 144, 624,  64, 429, 962, 213,
         7, 196, 451, 173, 492, 600, 466, 288, 352,  47,  30, 991, 638,
       117,  71, 728, 175, 855, 811, 802, 899,  31, 475, 221, 647, 274,
       548,  97, 132, 986, 969, 129, 809, 573, 654, 593, 110, 184, 819,
       179, 442, 204, 479, 715, 157, 226,  14, 253, 458, 822,  45,  94,
       661, 897, 268, 906, 347,  37, 390, 598, 397, 349, 514, 200, 171,
         6, 549, 515, 864, 785, 328, 491, 605, 237, 462, 657, 857, 585,
       508, 321, 516, 833,  40,   8, 582, 370, 737,  46, 719, 440, 389,
       356,  54, 652, 868, 528, 683, 413, 695, 308, 186, 806, 663, 545,
         3, 496, 646, 766, 862, 108, 778, 997, 860, 482, 380, 617,  15,
       388, 773, 839, 653, 679, 951, 902, 471, 539, 151, 587, 970, 921,
       765, 418, 580, 642, 217,  29, 597, 829, 252, 477, 775, 225, 314,
       325, 332, 717, 337, 267,  76, 309,  89,  84, 464, 524, 523, 682,
       745, 453, 784, 612, 381, 342, 345, 568, 511, 206, 153, 420, 540,
       699, 410, 446, 203, 245, 303, 142, 569, 494, 257, 512,  80])

In [44]:
#create a new column with new index
df['new index']=new_index

In [45]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new index
458,female,group E,bachelor's degree,standard,none,100,100,100,996
916,male,group E,bachelor's degree,standard,completed,100,100,100,964
962,female,group E,associate's degree,standard,none,100,100,100,640
149,male,group E,associate's degree,free/reduced,completed,100,100,93,141
625,male,group D,some college,standard,completed,100,97,99,908
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,569
787,female,group B,some college,standard,none,19,38,32,494
17,female,group B,some high school,free/reduced,none,18,32,28,257
980,female,group B,high school,free/reduced,none,8,24,23,512
59,female,group C,some high school,free/reduced,none,0,17,10,80

In [56]:
df.set_index('new_index',inplace=True)
df

KeyError: "None of ['new_index'] are in the columns"

In [57]:
#sort dataframe by new index
df.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new index,,,,,,,,
0,male,group C,some high school,free/reduced,none,68,63,54
1,male,group C,bachelor's degree,standard,none,58,55,48
2,female,group B,some college,standard,none,82,85,87
3,male,group D,some high school,free/reduced,none,45,37,37
4,male,group D,some college,standard,none,88,73,78
...,...,...,...,...,...,...,...,...
995,male,group E,some college,standard,none,76,71,72
996,female,group E,bachelor's degree,standard,none,100,100,100
997,female,group C,some high school,free/reduced,none,44,50,51
998,female,group D,some college,standard,none,98,100,99
999,male,group D,associate's degree,standard,none,81,71,73

In [58]:
#sort decending by index
df.sort_index(ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new index,,,,,,,,
999,male,group D,associate's degree,standard,none,81,71,73
998,female,group D,some college,standard,none,98,100,99
997,female,group C,some high school,free/reduced,none,44,50,51
996,female,group E,bachelor's degree,standard,none,100,100,100
995,male,group E,some college,standard,none,76,71,72
...,...,...,...,...,...,...,...,...
4,male,group D,some college,standard,none,88,73,78
3,male,group D,some high school,free/reduced,none,45,37,37
2,female,group B,some college,standard,none,82,85,87
1,male,group C,bachelor's degree,standard,none,58,55,48
0,male,group C,some high school,free/reduced,none,68,63,54