In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

In [ ]:
uploded=files.upload()

Saving StudentsPerformance.csv to StudentsPerformance.csv

In [ ]:
df=pd.read_csv("/content/StudentsPerformance.csv")

In [ ]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [ ]:
type(df['gender'])

pandas.core.series.Series

In [ ]:
df['gender'].index
df['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [ ]:
#syntax
df.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [ ]:
#selecting two or more column
#select 2 column using [[]]
df[['gender','math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [ ]:
type([['gender','math score ']])

list

In [ ]:
df[['gender','math score','reading score','writing score']]

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

In [ ]:
#We can't select 2 or more columns with the "."
df.'gender' 'math score '

SyntaxError: invalid syntax (2440989321.py, line 2)

In [22]:
#adding new column in the table
df['language score ']=80

In [23]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,80
1,female,group C,some college,standard,completed,69,90,88,80
2,female,group B,master's degree,standard,none,90,95,93,80
3,male,group A,associate's degree,free/reduced,none,47,57,44,80
4,male,group C,some college,standard,none,76,78,75,80
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,80
996,male,group C,high school,free/reduced,none,62,55,55,80
997,female,group C,high school,free/reduced,completed,59,71,65,80
998,female,group D,some college,standard,completed,68,78,77,80
999,female,group D,some college,free/reduced,none,77,86,86,80

In [24]:
#adding a new column with an array
import numpy as np

In [26]:
language_score =np.arange(0,1000)

In [27]:
len(language_score)

1000

In [28]:
df['language score']=language_score

In [29]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,80,0
1,female,group C,some college,standard,completed,69,90,88,80,1
2,female,group B,master's degree,standard,none,90,95,93,80,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,80,3
4,male,group C,some college,standard,none,76,78,75,80,4
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,80,995
996,male,group C,high school,free/reduced,none,62,55,55,80,996
997,female,group C,high school,free/reduced,completed,59,71,65,80,997
998,female,group D,some college,standard,completed,68,78,77,80,998
999,female,group D,some college,free/reduced,none,77,86,86,80,999

In [32]:
#create random integer numbers between 1 and 100
int_language_score =np.random.uniform(1,100,size=1000)

In [33]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,80,0
1,female,group C,some college,standard,completed,69,90,88,80,1
2,female,group B,master's degree,standard,none,90,95,93,80,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,80,3
4,male,group C,some college,standard,none,76,78,75,80,4
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,80,995
996,male,group C,high school,free/reduced,none,62,55,55,80,996
997,female,group C,high school,free/reduced,completed,59,71,65,80,997
998,female,group D,some college,standard,completed,68,78,77,80,998
999,female,group D,some college,free/reduced,none,77,86,86,80,999

In [34]:
df['language score']=int_language_score

In [35]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,80,42.172365
1,female,group C,some college,standard,completed,69,90,88,80,10.807148
2,female,group B,master's degree,standard,none,90,95,93,80,59.156038
3,male,group A,associate's degree,free/reduced,none,47,57,44,80,96.239657
4,male,group C,some college,standard,none,76,78,75,80,2.542639
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,80,44.097185
996,male,group C,high school,free/reduced,none,62,55,55,80,36.461984
997,female,group C,high school,free/reduced,completed,59,71,65,80,53.547616
998,female,group D,some college,standard,completed,68,78,77,80,30.108604
999,female,group D,some college,free/reduced,none,77,86,86,80,20.864631

In [36]:

# rounding the values of the dataset
round(df, 2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,80,42.17
1,female,group C,some college,standard,completed,69,90,88,80,10.81
2,female,group B,master's degree,standard,none,90,95,93,80,59.16
3,male,group A,associate's degree,free/reduced,none,47,57,44,80,96.24
4,male,group C,some college,standard,none,76,78,75,80,2.54
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,80,44.10
996,male,group C,high school,free/reduced,none,62,55,55,80,36.46
997,female,group C,high school,free/reduced,completed,59,71,65,80,53.55
998,female,group D,some college,standard,completed,68,78,77,80,30.11
999,female,group D,some college,free/reduced,none,77,86,86,80,20.86

In [37]:
1/2

0.5