In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://www.football-data.co.uk/mmz4281/2526/E0.csv")

In [3]:
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

In [5]:

root = "https://www.football-data.co.uk/mmz4281/"

In [7]:
# creating list of leagues
leagues = ['E0','E2', 'E3']

frames = []
# looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv(root + "2526" + "/"  + league + ".csv")
    frames.append(df)

In [9]:
frames[1]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E2,01/08/2025,20:00,Luton,AFC Wimbledon,1,0,H,0,0,...,1.93,1.93,1.93,1.95,1.98,1.93,1.91,1.82,1.94,2.01
1,E2,02/08/2025,12:30,Cardiff,Peterboro,2,1,H,0,1,...,1.85,2.00,1.87,2.03,1.90,2.00,1.85,1.88,1.93,2.04
2,E2,02/08/2025,15:00,Blackpool,Stevenage,2,3,A,1,2,...,1.93,1.93,1.94,1.94,1.94,1.93,1.84,1.87,1.94,2.04
3,E2,02/08/2025,15:00,Bradford,Wycombe,2,1,H,2,0,...,1.73,2.08,1.90,1.99,1.77,2.20,1.72,2.02,1.80,2.22
4,E2,02/08/2025,15:00,Burton,Mansfield,2,1,H,1,0,...,2.00,1.85,1.69,2.26,2.00,1.85,1.93,1.79,2.04,1.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E2,02/05/2026,15:00,Peterboro,Doncaster,1,3,A,0,0,...,2.05,1.80,NaN,NaN,2.05,1.80,1.99,1.75,NaN,NaN
548,E2,02/05/2026,15:00,Port Vale,Lincoln,0,2,A,0,1,...,1.98,1.88,NaN,NaN,1.98,1.90,1.91,1.82,NaN,NaN
549,E2,02/05/2026,15:00,Reading,Blackpool,0,1,A,0,0,...,2.03,1.83,NaN,NaN,2.03,1.83,1.94,1.78,NaN,NaN
550,E2,02/05/2026,15:00,Stevenage,Wigan,1,0,H,0,0,...,2.03,1.83,NaN,NaN,2.03,1.85,1.93,1.80,NaN,NaN
551,E2,02/05/2026,15:00,Wycombe,Rotherham,3,2,H,2,2,...,1.75,2.05,NaN,NaN,1.83,2.10,1.72,2.01,NaN,NaN

In [11]:
df=pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/E0.csv")

In [12]:
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,19/05/2024,16:00,Crystal Palace,Aston Villa,5,0,H,2,0,...,2.78,-0.75,1.73,2.08,1.78,2.16,1.93,2.21,1.81,2.05
376,E0,19/05/2024,16:00,Liverpool,Wolves,2,0,H,2,0,...,5.17,-2.75,2.07,1.86,2.04,1.85,2.10,1.89,2.04,1.82
377,E0,19/05/2024,16:00,Luton,Fulham,2,4,A,1,2,...,2.69,0.25,2.00,1.93,1.99,1.93,2.02,1.94,1.96,1.91
378,E0,19/05/2024,16:00,Man City,West Ham,3,1,H,2,1,...,4.82,-3.00,2.03,1.90,1.99,1.90,2.05,1.99,1.96,1.91
379,E0,19/05/2024,16:00,Sheffield United,Tottenham,0,3,A,0,1,...,3.81,1.50,2.06,1.87,2.05,1.88,2.08,1.89,2.01,1.86

In [15]:
df=df.rename(columns={'Date':'date','Home Team':'home team ','Away Team':'away team','FTHG':'home_goals','FTHG':'away goals'})

In [16]:
df

,Div,date,Time,HomeTeam,AwayTeam,away goals,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,19/05/2024,16:00,Crystal Palace,Aston Villa,5,0,H,2,0,...,2.78,-0.75,1.73,2.08,1.78,2.16,1.93,2.21,1.81,2.05
376,E0,19/05/2024,16:00,Liverpool,Wolves,2,0,H,2,0,...,5.17,-2.75,2.07,1.86,2.04,1.85,2.10,1.89,2.04,1.82
377,E0,19/05/2024,16:00,Luton,Fulham,2,4,A,1,2,...,2.69,0.25,2.00,1.93,1.99,1.93,2.02,1.94,1.96,1.91
378,E0,19/05/2024,16:00,Man City,West Ham,3,1,H,2,1,...,4.82,-3.00,2.03,1.90,1.99,1.90,2.05,1.99,1.96,1.91
379,E0,19/05/2024,16:00,Sheffield United,Tottenham,0,3,A,0,1,...,3.81,1.50,2.06,1.87,2.05,1.88,2.08,1.89,2.01,1.86

In [17]:
#READ CSV FILES FROM MULTIPLE URLS EITH PANDAS

In [31]:
root=("https://www.football-data.co.uk/mmz4281/")

In [50]:
#creating list of leagues
leagues=['E1','E2','E3']

frames=[]
for league in leagues:
  df= pd.read_csv(root+ "2324" + "/" + league + ".csv")
  frames.append(df)

In [54]:
frames[2].head(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,05/08/2023,15:00,Accrington,Newport County,3,0,H,1,0,...,1.74,-0.25,2.0,1.80,2.07,1.83,2.12,1.83,2.05,1.75
1,E3,05/08/2023,15:00,Crawley Town,Bradford,1,0,H,1,0,...,1.77,0.50,1.9,1.95,1.91,1.98,1.94,1.99,1.86,1.92
2,E3,05/08/2023,15:00,Crewe,Mansfield,2,2,D,1,2,...,1.94,0.50,2.0,1.85,2.01,1.88,2.06,1.89,1.96,1.82

In [53]:
frames[1].tail(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
549,E2,27/04/2024,12:30,Stevenage,Cheltenham,2,1,H,1,0,...,1.77,0.00,1.85,2.00,1.86,2.03,1.89,2.09,1.85,1.97
550,E2,27/04/2024,12:30,Wigan,Bristol Rvs,2,0,H,1,0,...,2.03,-0.25,1.83,2.03,1.83,2.07,1.85,2.07,1.80,2.01
551,E2,27/04/2024,12:30,Wycombe,Charlton,1,0,H,1,0,...,2.11,-0.25,2.03,1.83,2.03,1.86,2.11,1.90,2.01,1.80

In [80]:
#multiple season
leagues=['E1','E2','E3']

frames=[]
for league in leagues:
  for season in range (20,26):
    df= pd.read_csv(root + str(season) + str(season+1) + "/" + league + ".csv")
    df.insert(1,'season','season')
    frames.append(df)

In [58]:
len(frames)

18

In [60]:
frames[12]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,season,12/09/2020,15:00,Barrow,Stevenage,1,1,D,1,...,1.76,-0.25,1.95,1.90,1.93,1.98,1.98,1.99,1.91,1.92
1,E3,season,12/09/2020,15:00,Bolton,Forest Green,0,1,A,0,...,1.79,-0.25,2.02,1.83,2.04,1.87,2.09,1.90,2.00,1.83
2,E3,season,12/09/2020,15:00,Bradford,Colchester,0,0,D,0,...,1.65,-0.25,2.07,1.72,2.11,1.82,2.20,1.82,2.09,1.76
3,E3,season,12/09/2020,15:00,Cambridge,Carlisle,3,0,H,2,...,1.70,-0.25,1.98,1.88,2.02,1.88,2.04,1.90,1.99,1.84
4,E3,season,12/09/2020,15:00,Cheltenham,Morecambe,1,2,A,1,...,1.75,-0.50,1.83,2.02,1.87,2.04,1.88,2.09,1.83,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,season,08/05/2021,15:00,Port Vale,Mansfield,0,3,A,0,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
548,E3,season,08/05/2021,15:00,Scunthorpe,Stevenage,0,1,A,0,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
549,E3,season,08/05/2021,15:00,Southend,Newport County,1,1,D,1,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,season,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,season,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

In [61]:
import pandas as pd

In [63]:
df=pd.read_csv("https://www.football-data.co.uk/mmz4281/0809/E0.csv")

In [64]:
df

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA
0,E0,16/08/08,Arsenal,West Brom,1,0,H,1,0,H,...,1.71,1.65,2.25,2.14,26,-1.5,1.88,1.81,2.12,1.97
1,E0,16/08/08,Bolton,Stoke,3,1,H,3,0,H,...,2.33,2.16,1.70,1.64,27,0.0,1.35,1.31,3.56,3.27
2,E0,16/08/08,Everton,Blackburn,2,3,A,1,1,D,...,2.34,2.17,1.70,1.63,28,0.0,1.73,1.43,3.05,2.76
3,E0,16/08/08,Hull,Fulham,2,1,H,1,1,D,...,2.32,2.15,1.69,1.64,26,0.0,1.91,1.85,2.07,1.94
4,E0,16/08/08,Middlesbrough,Tottenham,2,1,H,0,0,D,...,1.90,1.81,2.12,1.92,27,0.0,2.45,2.30,1.65,1.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/09,Liverpool,Tottenham,3,1,H,1,0,H,...,1.77,1.69,2.17,2.07,18,-1.0,2.12,2.06,1.85,1.79
376,E0,24/05/09,Man City,Bolton,1,0,H,1,0,H,...,1.76,1.71,2.19,2.04,18,-0.5,1.78,1.74,2.22,2.15
377,E0,24/05/09,Sunderland,Chelsea,2,3,A,0,0,D,...,1.99,1.88,1.98,1.86,18,0.5,2.01,1.97,1.94,1.91
378,E0,24/05/09,West Ham,Middlesbrough,2,1,H,1,0,H,...,1.92,1.87,2.01,1.87,19,0.0,1.70,1.63,2.40,2.21
379,E0,24/05/09,Wigan,Portsmouth,1,0,H,1,0,H,...,2.08,2.00,1.86,1.74,17,0.0,1.61,1.53,2.50,2.44

In [65]:
root=("https://www.football-data.co.uk/mmz4281/")

In [66]:
root

'https://www.football-data.co.uk/mmz4281/'

In [67]:
#creating list
leagues=['E0','E1','E2']

frames=[]
for league in leagues:
  df=pd.read_csv(root + "2021" + "/" + league + ".csv")
  frames.append(df)

In [77]:
len(frames)

3

In [78]:
frames[1].head(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E2,12/09/2020,15:00,Accrington,Peterboro,2,0,H,1,0,...,2.03,0.25,2.02,1.83,2.08,1.83,2.09,1.87,2.02,1.81
1,E2,12/09/2020,15:00,Crewe,Charlton,0,2,A,0,2,...,1.88,0.00,1.95,1.90,1.96,1.94,2.00,1.95,1.94,1.89
2,E2,12/09/2020,15:00,Doncaster,Milton Keynes Dons,1,1,D,0,0,...,1.69,-0.25,1.80,2.05,1.81,2.12,1.85,2.12,1.80,2.05

In [79]:
frames[2].tail(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
549,E3,08/05/2021,15:00,Southend,Newport County,1,1,D,1,0,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,0,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

In [86]:
#multiple seasons
leagues=['E0','E1','E2']

frames=[]
for league in leagues:
  for season in range (20,26):
    df=pd.read_csv(root + str(season)+str(season+1)+"/" +league + "csv")
    df.insert(2,'season',season)
    frames.append(df)

In [82]:
len(frames)

18

In [88]:
frames[15]

,Div,Date,season,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E2,05/08/2023,23,15:00,Barnsley,Port Vale,7,0,H,2,...,1.75,-0.75,2.03,1.83,2.07,1.83,2.09,1.85,2.01,1.80
1,E2,05/08/2023,23,15:00,Blackpool,Burton,2,0,H,2,...,2.10,-0.75,1.93,1.93,1.94,1.94,1.96,1.97,1.88,1.91
2,E2,05/08/2023,23,15:00,Bolton,Lincoln,3,0,H,1,...,1.67,-0.75,2.00,1.85,2.01,1.88,2.02,1.92,1.96,1.84
3,E2,05/08/2023,23,15:00,Cambridge,Oxford,2,0,H,2,...,1.71,0.25,1.93,1.93,1.95,1.93,2.00,1.98,1.90,1.90
4,E2,05/08/2023,23,15:00,Carlisle,Fleetwood Town,1,1,D,1,...,1.62,-0.25,2.00,1.85,2.07,1.83,2.08,1.90,2.00,1.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E2,27/04/2024,23,12:30,Reading,Blackpool,3,2,H,1,...,2.25,0.50,1.90,1.95,1.90,1.99,1.91,2.10,1.83,1.96
548,E2,27/04/2024,23,12:30,Shrewsbury,Leyton Orient,1,3,A,0,...,1.74,-0.25,2.00,1.85,2.04,1.86,2.25,1.86,2.06,1.76
549,E2,27/04/2024,23,12:30,Stevenage,Cheltenham,2,1,H,1,...,1.77,0.00,1.85,2.00,1.86,2.03,1.89,2.09,1.85,1.97
550,E2,27/04/2024,23,12:30,Wigan,Bristol Rvs,2,0,H,1,...,2.03,-0.25,1.83,2.03,1.83,2.07,1.85,2.07,1.80,2.01
551,E2,27/04/2024,23,12:30,Wycombe,Charlton,1,0,H,1,...,2.11,-0.25,2.03,1.83,2.03,1.86,2.11,1.90,2.01,1.80

In [89]:
#dictionary
dict_countries={
    'E0':'England',
    'D1':'Germany',
    'I1':'Ilaly',
    'F1':'France'

}

In [91]:
dict_countries['F1']

'France'

In [97]:
dict_historical_data={}

for league_code in dict_countries:
  frames_for_current_league = []
  for season in range (15,20):
    # Corrected: Use league_code (e.g., 'E0') directly as filename
    df=pd.read_csv(root + str(season)+ str(season+1)+ "/" + league_code + ".csv")
    df.insert(1,'season',season)
    frames_for_current_league.append(df)

  # Concatenate all seasons for the current league after the inner loop finishes
  df_current_league = pd.concat(frames_for_current_league, ignore_index=True)
  dict_historical_data[league_code] = df_current_league

# Concatenate all leagues into a master DataFrame after the outer loop finishes
df_master = pd.concat(dict_historical_data.values(), ignore_index=True)
df_master.to_csv("all_leagues_historical_data.csv",index=False)

In [98]:
dict_historical_data['F1']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,F1,15,07/08/15,Lille,Paris SG,0.0,1.0,A,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,F1,15,08/08/15,Bastia,Rennes,2.0,1.0,H,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,F1,15,08/08/15,Marseille,Caen,0.0,1.0,A,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,F1,15,08/08/15,Montpellier,Angers,0.0,2.0,A,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,F1,15,08/08/15,Nantes,Guingamp,1.0,0.0,H,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1795,F1,19,07/03/2020,Nice,Monaco,2.0,1.0,H,0.0,1.0,...,2.38,0.25,2.06,1.87,2.07,1.85,2.09,1.90,2.01,1.84
1796,F1,19,07/03/2020,Reims,Brest,1.0,0.0,H,1.0,0.0,...,1.54,-0.50,2.01,1.92,2.02,1.89,2.05,1.93,1.99,1.86
1797,F1,19,08/03/2020,St Etienne,Bordeaux,1.0,1.0,D,0.0,0.0,...,1.61,-0.25,2.03,1.90,2.00,1.92,2.07,1.98,1.94,1.91
1798,F1,19,08/03/2020,Rennes,Montpellier,5.0,0.0,H,2.0,0.0,...,1.60,-0.25,1.97,1.96,1.97,1.95,2.00,2.00,1.94,1.91
1799,F1,19,08/03/2020,Lille,Lyon,1.0,0.0,H,1.0,0.0,...,1.70,-0.25,1.89,2.04,1.89,2.02,1.97,2.06,1.87,1.98