In [4]:
import requests
import pandas as pd
from io import StringIO
from bs4 import BeautifulSoup

In [9]:
url="https://en.wikipedia.org/wiki/List_of_largest_companies_in_India"

In [20]:
headers = {
    "User-Agent": "MyDataAnalysisBot/1.0 (your_email@example.com)"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

# Step 1: Use find_all to get a list of all matching tables
all_tables = soup.find_all('table', class_='wikitable sortable')
# Step 2: Create a list to store your DataFrames
dfs = []
# Step 3: Loop through each table found
for table in all_tables:
    # Use StringIO to wrap the string version of the table
    df = pd.read_html(StringIO(str(table)))[0]
    dfs.append(df)

pd.set_option('display.max_rows', 70)

# Print the first DataFrame to check the result
if dfs:
    print(dfs[0])

    Rank  Forbes  2000 rank                         Name Headquarters  \
0      1                 49  Reliance Industries Limited       Mumbai
1      2                 55          State Bank of India       Mumbai
2      3                 65                    HDFC Bank       Mumbai
3      4                 70   Life Insurance Corporation    New Delhi
4      5                142                   ICICI Bank       Mumbai
..   ...                ...                          ...          ...
66    65               1895     Dr. Reddy's Laboratories    Hyderabad
67    66               1908              Varun Beverages      Gurgaon
68    67               1949                        CIFCL      Chennai
69    68               1957                         NMDC    Hyderabad
70    69               1980                    ABB India    Bangalore

    Revenue (billions US$) Profit (billions US$)  Assets (billions US$)  \
0                    108.8                   8.4                  210.5
1                     71.8                   8.1                  807.4
2                     49.3                   7.7                  483.2
3                     98.0                   4.9                  561.4
4                     28.5                   5.3                  283.5
..                     ...                   ...                    ...
66                     3.4                   0.7                    4.6
67                     2.0                   0.3                    1.8
68                     2.3                   0.4                   18.8
69                     2.5                   0.8                    3.9
70                     1.3                   0.2                    1.3

    Value (billions US$)         Industry
0                  233.1     Conglomerate
1                   87.6          Banking
2                  133.6          Banking
3                   73.6        Insurance
4                   95.3          Banking
..                   ...              ...
66                  11.6  Pharmaceuticals
67                  23.6        Beverages
68                  13.0       Financials
69                   9.7           Mining
70                  21.3    Capital goods

[71 rows x 9 columns]

In [21]:
df

,Rank,Name,Industry,Revenue (in ₹ crore),Revenue growth,Profits (in ₹ crore),Headquarters,State controlled
0,1,Reliance Industries Limited,Conglomerate,997795,8%,69648,Mumbai,NaN
1,2,Life Insurance Corporation,Insurance,893465,4%,48320,Mumbai,Yes
2,3,Indian Oil Corporation,Oil and gas,766008,2%,13598,New Delhi,Yes
3,4,State Bank of India,Banking,663343,12%,77561,Mumbai,Yes
4,5,Oil and Natural Gas Corporation,Oil and gas,624805,0%,36226,New Delhi,Yes
5,6,HDFC Bank,Banking,470916,15%,70792,Mumbai,NaN
6,7,Tata Motors,Automotive,449357,2%,27830,Mumbai,NaN
7,8,Bharat Petroleum,Oil and gas,443948,2%,13337,Mumbai,Yes
8,9,ICICI Bank,Banking,294587,25%,51029,Mumbai,NaN
9,10,Larsen & Toubro,Capital goods,260745,16%,15037,Mumbai,NaN
10,11,Tata Consultancy Services,Infotech,259286,6%,48553,Mumbai,NaN
11,12,Hindalco Industries,Metals and mining,243534,13%,16001,Mumbai,NaN
12,13,Tata Steel,Iron and steel,220507,3%,3421,Mumbai,NaN
13,14,NTPC Limited,Utilities,196847,7%,23422,New Delhi,Yes
14,15,Bharti Airtel,Telecommunications,194387,26%,33556,New Delhi,NaN
15,16,JSW Steel Ltd,Iron and steel,168689,6%,26713,Mumbai,NaN
16,17,Infosys,Infotech,166590,6%,28165,Bangalore,NaN
17,18,Mahindra & Mahindra,Automotive,162941,13%,12929,Mumbai,NaN
18,19,Vedanta Resources,Metals and mining,160450,7%,14988,"London, UK",NaN
19,20,Maruti Suzuki India,Automotive,159407,8%,14500,New Delhi,NaN
20,21,Axis Bank,Banking,155917,13%,28055,Mumbai,Yes
21,22,Coal India,Metals and mining,155605,1%,35358,Kolkata,Yes
22,23,Bank of Baroda,Banking,152884,8%,20716,Vadodara,Yes
23,24,Canara Bank,Banking,152658,10%,17540,Bangalore,Yes
24,25,Grasim Industries,Diversified,151048,14%,3706,Mumbai,NaN
25,26,GAIL,Oil and gas,147417,8%,12450,New Delhi,Yes
26,27,Punjab National Bank,Banking,141570,15%,18480,New Delhi,Yes
27,28,Bajaj Finserv,Financials,133840,21%,8872,Pune,NaN
28,29,Nayara Energy,Oil and gas,130326,3%,6080,Mumbai,NaN
29,30,Union Bank of India,Banking,129979,10%,18027,Mumbai,Yes
30,31,HCL Technologies,Infotech,119488,7%,17390,Noida,NaN
31,32,Motherson Sumi Systems,Automotive,114502,16%,3803,Noida,NaN
32,33,Power Finance Corporation,Financial services,107203,17%,22991,New Delhi,Yes
33,34,Kotak Mahindra Bank,Banking,107095,14%,22126,Mumbai,NaN
34,35,Steel Authority of India,Iron and steel,103861,6%,2372,New Delhi,Yes
35,36,ITC Limited,Consumer goods,93705,31%,34747,Kolkata,NaN
36,37,Wipro,Infotech,92937,1%,13135,Bangalore,NaN
37,38,Flipkart,E-commerce,84230,18%,"−5,189",Bangalore,NaN
38,39,IndiGo,Airline,84098,18%,7258,Gurgaon,NaN
39,40,Bank of India,Banking,80625,19%,9548,Mumbai,Yes
40,41,Indian Bank,Banking,72051,12%,11261,Chennai,Yes
41,42,Hyundai Motor India,Automotive,70282,2%,5640,Gurgaon,NaN
42,43,Tata Power,Utilities,68892,6%,3971,Mumbai,NaN
43,44,Titan Company,Gems and jewellery,68758,27%,3337,Bangalore,NaN
44,45,Toyota Kirloskar Motor,Automotive,65958,16%,5672,Bidadi,NaN
45,46,Hindustan Unilever,Consumer goods,64891,3%,10649,Mumbai,NaN
46,47,Adani Enterprises,Trading,62652,12%,7112,Ahmedabad,NaN
47,48,AWL Agri Business,Consumer goods,61387,24%,1226,Ahmedabad,NaN
48,49,Avenue Supermarts,Retail,60599,17%,2708,Mumbai,NaN
49,50,NABARD,Finance,59292,20%,7803,Mumbai,Yes

In [22]:
pd.set_option('display.max_rows', 70)

In [23]:
df

,Rank,Name,Industry,Revenue (in ₹ crore),Revenue growth,Profits (in ₹ crore),Headquarters,State controlled
0,1,Reliance Industries Limited,Conglomerate,997795,8%,69648,Mumbai,NaN
1,2,Life Insurance Corporation,Insurance,893465,4%,48320,Mumbai,Yes
2,3,Indian Oil Corporation,Oil and gas,766008,2%,13598,New Delhi,Yes
3,4,State Bank of India,Banking,663343,12%,77561,Mumbai,Yes
4,5,Oil and Natural Gas Corporation,Oil and gas,624805,0%,36226,New Delhi,Yes
5,6,HDFC Bank,Banking,470916,15%,70792,Mumbai,NaN
6,7,Tata Motors,Automotive,449357,2%,27830,Mumbai,NaN
7,8,Bharat Petroleum,Oil and gas,443948,2%,13337,Mumbai,Yes
8,9,ICICI Bank,Banking,294587,25%,51029,Mumbai,NaN
9,10,Larsen & Toubro,Capital goods,260745,16%,15037,Mumbai,NaN
10,11,Tata Consultancy Services,Infotech,259286,6%,48553,Mumbai,NaN
11,12,Hindalco Industries,Metals and mining,243534,13%,16001,Mumbai,NaN
12,13,Tata Steel,Iron and steel,220507,3%,3421,Mumbai,NaN
13,14,NTPC Limited,Utilities,196847,7%,23422,New Delhi,Yes
14,15,Bharti Airtel,Telecommunications,194387,26%,33556,New Delhi,NaN
15,16,JSW Steel Ltd,Iron and steel,168689,6%,26713,Mumbai,NaN
16,17,Infosys,Infotech,166590,6%,28165,Bangalore,NaN
17,18,Mahindra & Mahindra,Automotive,162941,13%,12929,Mumbai,NaN
18,19,Vedanta Resources,Metals and mining,160450,7%,14988,"London, UK",NaN
19,20,Maruti Suzuki India,Automotive,159407,8%,14500,New Delhi,NaN
20,21,Axis Bank,Banking,155917,13%,28055,Mumbai,Yes
21,22,Coal India,Metals and mining,155605,1%,35358,Kolkata,Yes
22,23,Bank of Baroda,Banking,152884,8%,20716,Vadodara,Yes
23,24,Canara Bank,Banking,152658,10%,17540,Bangalore,Yes
24,25,Grasim Industries,Diversified,151048,14%,3706,Mumbai,NaN
25,26,GAIL,Oil and gas,147417,8%,12450,New Delhi,Yes
26,27,Punjab National Bank,Banking,141570,15%,18480,New Delhi,Yes
27,28,Bajaj Finserv,Financials,133840,21%,8872,Pune,NaN
28,29,Nayara Energy,Oil and gas,130326,3%,6080,Mumbai,NaN
29,30,Union Bank of India,Banking,129979,10%,18027,Mumbai,Yes
30,31,HCL Technologies,Infotech,119488,7%,17390,Noida,NaN
31,32,Motherson Sumi Systems,Automotive,114502,16%,3803,Noida,NaN
32,33,Power Finance Corporation,Financial services,107203,17%,22991,New Delhi,Yes
33,34,Kotak Mahindra Bank,Banking,107095,14%,22126,Mumbai,NaN
34,35,Steel Authority of India,Iron and steel,103861,6%,2372,New Delhi,Yes
35,36,ITC Limited,Consumer goods,93705,31%,34747,Kolkata,NaN
36,37,Wipro,Infotech,92937,1%,13135,Bangalore,NaN
37,38,Flipkart,E-commerce,84230,18%,"−5,189",Bangalore,NaN
38,39,IndiGo,Airline,84098,18%,7258,Gurgaon,NaN
39,40,Bank of India,Banking,80625,19%,9548,Mumbai,Yes
40,41,Indian Bank,Banking,72051,12%,11261,Chennai,Yes
41,42,Hyundai Motor India,Automotive,70282,2%,5640,Gurgaon,NaN
42,43,Tata Power,Utilities,68892,6%,3971,Mumbai,NaN
43,44,Titan Company,Gems and jewellery,68758,27%,3337,Bangalore,NaN
44,45,Toyota Kirloskar Motor,Automotive,65958,16%,5672,Bidadi,NaN
45,46,Hindustan Unilever,Consumer goods,64891,3%,10649,Mumbai,NaN
46,47,Adani Enterprises,Trading,62652,12%,7112,Ahmedabad,NaN
47,48,AWL Agri Business,Consumer goods,61387,24%,1226,Ahmedabad,NaN
48,49,Avenue Supermarts,Retail,60599,17%,2708,Mumbai,NaN
49,50,NABARD,Finance,59292,20%,7803,Mumbai,Yes

In [25]:
dfs[0]

,Rank,Forbes 2000 rank,Name,Headquarters,Revenue (billions US$),Profit (billions US$),Assets (billions US$),Value (billions US$),Industry
0,1,49,Reliance Industries Limited,Mumbai,108.8,8.4,210.5,233.1,Conglomerate
1,2,55,State Bank of India,Mumbai,71.8,8.1,807.4,87.6,Banking
2,3,65,HDFC Bank,Mumbai,49.3,7.7,483.2,133.6,Banking
3,4,70,Life Insurance Corporation,New Delhi,98.0,4.9,561.4,73.6,Insurance
4,5,142,ICICI Bank,Mumbai,28.5,5.3,283.5,95.3,Banking
...,...,...,...,...,...,...,...,...,...
66,65,1895,Dr. Reddy's Laboratories,Hyderabad,3.4,0.7,4.6,11.6,Pharmaceuticals
67,66,1908,Varun Beverages,Gurgaon,2.0,0.3,1.8,23.6,Beverages
68,67,1949,CIFCL,Chennai,2.3,0.4,18.8,13.0,Financials
69,68,1957,NMDC,Hyderabad,2.5,0.8,3.9,9.7,Mining
70,69,1980,ABB India,Bangalore,1.3,0.2,1.3,21.3,Capital goods

In [26]:
pd.set_option('display.max_rows', 70)
dfs[0]

,Rank,Forbes 2000 rank,Name,Headquarters,Revenue (billions US$),Profit (billions US$),Assets (billions US$),Value (billions US$),Industry
0,1,49,Reliance Industries Limited,Mumbai,108.8,8.4,210.5,233.1,Conglomerate
1,2,55,State Bank of India,Mumbai,71.8,8.1,807.4,87.6,Banking
2,3,65,HDFC Bank,Mumbai,49.3,7.7,483.2,133.6,Banking
3,4,70,Life Insurance Corporation,New Delhi,98.0,4.9,561.4,73.6,Insurance
4,5,142,ICICI Bank,Mumbai,28.5,5.3,283.5,95.3,Banking
...,...,...,...,...,...,...,...,...,...
66,65,1895,Dr. Reddy's Laboratories,Hyderabad,3.4,0.7,4.6,11.6,Pharmaceuticals
67,66,1908,Varun Beverages,Gurgaon,2.0,0.3,1.8,23.6,Beverages
68,67,1949,CIFCL,Chennai,2.3,0.4,18.8,13.0,Financials
69,68,1957,NMDC,Hyderabad,2.5,0.8,3.9,9.7,Mining
70,69,1980,ABB India,Bangalore,1.3,0.2,1.3,21.3,Capital goods

In [27]:
dfs[0]

,Rank,Forbes 2000 rank,Name,Headquarters,Revenue (billions US$),Profit (billions US$),Assets (billions US$),Value (billions US$),Industry
0,1,49,Reliance Industries Limited,Mumbai,108.8,8.4,210.5,233.1,Conglomerate
1,2,55,State Bank of India,Mumbai,71.8,8.1,807.4,87.6,Banking
2,3,65,HDFC Bank,Mumbai,49.3,7.7,483.2,133.6,Banking
3,4,70,Life Insurance Corporation,New Delhi,98.0,4.9,561.4,73.6,Insurance
4,5,142,ICICI Bank,Mumbai,28.5,5.3,283.5,95.3,Banking
...,...,...,...,...,...,...,...,...,...
66,65,1895,Dr. Reddy's Laboratories,Hyderabad,3.4,0.7,4.6,11.6,Pharmaceuticals
67,66,1908,Varun Beverages,Gurgaon,2.0,0.3,1.8,23.6,Beverages
68,67,1949,CIFCL,Chennai,2.3,0.4,18.8,13.0,Financials
69,68,1957,NMDC,Hyderabad,2.5,0.8,3.9,9.7,Mining
70,69,1980,ABB India,Bangalore,1.3,0.2,1.3,21.3,Capital goods

In [28]:
pd.set_option('display.max_rows', 70)

In [31]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(dfs[0].to_string())

    Rank  Forbes  2000 rank                                Name Headquarters  Revenue (billions US$) Profit (billions US$)  Assets (billions US$)  Value (billions US$)               Industry
0      1                 49         Reliance Industries Limited       Mumbai                   108.8                   8.4                  210.5                 233.1           Conglomerate
1      2                 55                 State Bank of India       Mumbai                    71.8                   8.1                  807.4                  87.6                Banking
2      3                 65                           HDFC Bank       Mumbai                    49.3                   7.7                  483.2                 133.6                Banking
3      4                 70          Life Insurance Corporation    New Delhi                    98.0                   4.9                  561.4                  73.6              Insurance
4      5                142                          ICICI Bank       Mumbai                    28.5                   5.3                  283.5                  95.3                Banking
5      6                207     Oil and Natural Gas Corporation    New Delhi                    77.5                   5.1                   80.6                  41.9            Oil and gas
6      7                259              Indian Oil Corporation    New Delhi                    93.8                   5.0                   57.8                  27.8            Oil and gas
7      8                284                         Tata Motors       Mumbai                    52.9                   3.8                   44.4                  43.8             Automotive
8      9                293                           Axis Bank       Mumbai                    16.7                   3.2                  182.0                  42.3                Banking
9     10                372                        NTPC Limited    New Delhi                    21.2                   2.4                   54.7                  42.5              Utilities
10    11                398                     Larsen & Toubro       Mumbai                    26.7                   1.6                   40.7                  56.9          Capital goods
11    12                412           Tata Consultancy Services       Mumbai                    29.1                   5.5                   17.6                 166.5               Infotech
12    13                440                      Bank of Baroda     Vadodara                    17.1                   2.3                  198.4                  16.2                Banking
13    14                442                 Kotak Mahindra Bank       Mumbai                    11.4                   2.2                   92.0                  40.5                Banking
14    15                472                       Bharti Airtel    New Delhi                    18.1                   0.9                   53.3                  91.5      Telecommunication
15    16                488                          Coal India      Kolkata                    17.2                   3.9                   28.5                  34.8      Metals and mining
16    17                525                         Canara Bank    Bangalore                    16.8                   1.8                  184.0                  12.4                Banking
17    18                533           Power Finance Corporation    New Delhi                    11.1                   2.4                  124.6                  18.5             Financials
18    19                537                    Bharat Petroleum       Mumbai                    54.1                   3.2                   24.3                  16.4            Oil and gas
19    20                569                             Infosys    Bangalore                    18.6                   3.2                   16.5                  71.9               Infotech
20    21                571                Punjab National Bank    New Delhi                    14.8                   1.1                  191.7                  16.5                Banking
21    22                575                 Union Bank of India       Mumbai                    14.3                   1.7                  168.1                  12.7                Banking
22    23                592                       Bajaj Finserv         Pune                    13.0                   1.0                   64.5                  30.3             Financials
23    24                593                 Mahindra & Mahindra       Mumbai                    16.8                   1.4                   28.3                  37.5             Automotive
24    25                645                       JSW Steel Ltd       Mumbai                    21.1                   1.1                   27.4                  26.6         Iron and steel
25    26                684                 Hindalco Industries       Mumbai                    26.1                   1.1                   27.1                  17.7      Metals and mining
26    27                746                   Grasim Industries       Mumbai                    15.3                   0.7                   47.0                  19.8            Diversified
27    28                764                    HCL Technologies        Noida                    13.3                   1.9                   12.0                  43.4               Infotech
28    29                810                         ITC Limited      Kolkata                     8.5                   2.5                   10.5                  65.4         Consumer goods
29    30                827     Power Grid Corporation of India      Gurgaon                     5.6                   1.9                   29.6                  35.0              Utilities
30    31                834                          Tata Steel      Kolkata                    28.3                  −0.4                   32.7                  25.1         Iron and steel
31    32                901                       IndusInd Bank       Mumbai                     6.7                   1.1                   61.8                  13.2                Banking
32    33                922  Indian Railway Finance Corporation    New Delhi                     3.2                   0.7                   58.6                  26.5             Financials
33    34                926                               Wipro    Bangalore                    10.8                   1.3                   13.8                  28.9               Infotech
34    35                930                                GAIL    New Delhi                    16.1                   1.2                   15.0                  16.1            Oil and gas
35    36                947                         Indian Bank      Chennai                     7.8                   1.0                   95.4                   8.7                Banking
36    37                961                     Vedanta Limited       Mumbai                    17.4                   0.5                   22.9                  19.7      Metals and mining
37    38               1048                         Adani Power    Ahmedabad                     6.1                   2.5                   11.1                  29.4                 Energy
38    39               1053                       Bank of India       Mumbai                     8.1                   0.8                  110.8                   6.7                Banking
39    40               1059                   Adani Enterprises    Ahmedabad                    12.7                   0.4                   19.3                  41.9                Holding
40    41               1161                  Sun Pharmaceutical       Mumbai                     5.7                   1.1                    9.6                  44.1        Pharmaceuticals
41    42               1212                              IndiGo      Gurgaon                     7.9                   0.9                    8.8                  20.2                Airline
42    43               1219                   Adani Ports & SEZ    Ahmedabad                     3.2                   1.0                   14.3                  34.6               Shipping
43    44               1259                           IDBI Bank       Mumbai                     3.7                   0.7                   43.7                  10.9                Banking
44    45               1264                          Bajaj Auto         Pune                     5.4                   0.9                    4.7                  29.4             Automotive
45    46               1281           Shriram Transport Finance      Chennai                     4.4                   0.9                   29.8                  10.7             Financials
46    47               1384                        Asian Paints       Mumbai                     4.3                   0.7                    3.6                  32.3              Chemicals
47    48               1534                          Tata Power       Mumbai                     7.4                   0.5                   16.7                  16.7              Utilities
48    49               1562                       Titan Company    Bangalore                     6.2                   0.0                    2.3                   1.1     Gems and jewellery
49    50               1604              Jio Financial Services       Mumbai                     0.2                   0.2                   17.4                  27.2             Financials
50    49               1568                      Rajesh Exports    Bangalore                    32.6                   0.1                    4.1                   2.0     Gems and jewellery
51    50               1617                               DMart       Mumbai                     6.1                   0.3                    2.5                  36.6                 Retail
52    51               1693              Jindal Steel and Power    New Delhi                     6.0                   0.6                    9.4                  12.4         Iron and steel
53    52               1697                 LIC Housing Finance       Mumbai                     3.3                   0.4                   34.9                   4.3             Financials
54    53               1699                  Adani Green Energy    Ahmedabad                     1.1                   0.1                   10.6                  34.8       Renewable energy
55    54               1704         Bajaj Holdings & Investment       Mumbai                     0.2                   0.9                    7.8                  11.0                Holding
56    55               1760       General Insurance Corporation       Mumbai                     5.7                   0.9                   20.9                   7.2              Insurance
57    56               1769                            Yes Bank       Mumbai                     4.0                   0.2                   48.7                   8.3                Banking
58    57               1805              Motherson Sumi Systems        Noida                    11.4                   0.2                    9.4                  10.5             Automotive
59    58               1821                  Bharat Electronics    Bangalore                     2.2                   0.4                    4.4                  21.8  Aerospace and defense
60    59               1840               Central Bank of India       Mumbai                     4.3                   0.3                   53.7                   6.4                Banking
61    60               1842                 Bank of Maharashtra         Pune                     2.8                   0.5                   36.8                   5.5                Banking
62    61               1848                        Indus Towers      Gurgaon                     3.5                   0.7                    6.7                  11.1      Telecommunication
63    62               1853            Steel Authority of India    New Delhi                    12.9                   0.4                   15.6                   8.3         Iron and steel
64    63               1869                        Federal Bank        Kochi                     3.2                   0.5                   38.1                   4.8                Banking
65    64               1873                                 DLF      Gurgaon                     0.8                   0.3                    7.2                  25.2            Real estate
66    65               1895            Dr. Reddy's Laboratories    Hyderabad                     3.4                   0.7                    4.6                  11.6        Pharmaceuticals
67    66               1908                     Varun Beverages      Gurgaon                     2.0                   0.3                    1.8                  23.6              Beverages
68    67               1949                               CIFCL      Chennai                     2.3                   0.4                   18.8                  13.0             Financials
69    68               1957                                NMDC    Hyderabad                     2.5                   0.8                    3.9                   9.7                 Mining
70    69               1980                           ABB India    Bangalore                     1.3                   0.2                    1.3                  21.3          Capital goods