In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/rishirokde-official/Python-for-Data-Science/refs/heads/main/python-for-data-science-main/05.Data%20Extraction/players_20.csv")

In [ ]:
df

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18273,245006,https://sofifa.com/player/245006/shuai-shao/20...,Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
18274,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
18275,252332,https://sofifa.com/player/252332/wei-zhang/20/...,Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
18276,251110,https://sofifa.com/player/251110/haijian-wang/...,Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
18277,233449,https://sofifa.com/player/233449/ximing-pan/20...,Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [ ]:
df

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18273,245006,https://sofifa.com/player/245006/shuai-shao/20...,Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
18274,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
18275,252332,https://sofifa.com/player/252332/wei-zhang/20/...,Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
18276,251110,https://sofifa.com/player/251110/haijian-wang/...,Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
18277,233449,https://sofifa.com/player/233449/ximing-pan/20...,Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [ ]:
if 'short_name' in df.columns:
    df.set_index('short_name',inplace=True)

In [ ]:
df

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

Selecting with single value position

In [ ]:
#get the height of messi
df.iloc[0,5]

np.int64(170)

In [ ]:
#get the weight of neymar jr
df.iloc[2,6]

np.int64(68)

In [ ]:
#get all rowws height of all player
df.iloc[:,5]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [ ]:
#particular player info (neymar jr )
df.iloc[2,:]

sofifa_id                                                190871
player_url    https://sofifa.com/player/190871/neymar-da-sil...
long_name                         Neymar da Silva Santos Junior
age                                                          27
dob                                                  1992-02-05
                                    ...
lb                                                         61+3
lcb                                                        46+3
cb                                                         46+3
rcb                                                        46+3
rb                                                         61+3
Name: Neymar Jr, Length: 103, dtype: object

In [ ]:
#get all data of messi and neymar
df.iloc[[0,2]]

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3

In [ ]:
#get the height of messi and cr7
df.iloc[[0,1],5]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [80]:
#get the h and w of neymar
df.iloc[2,[5,6]]

height_cm    175
weight_kg     68
Name: Neymar Jr, dtype: object

In [83]:
#get height and weight of neymar  and messi
df.iloc[[0,2],[5,6]]

            height_cm  weight_kg
short_name
L. Messi          170         72
Neymar Jr         175         68

Selecting a range of data with a slice

In [90]:
players=[0,2]
df.iloc[players,1:3]

,player_url,long_name
short_name,,
L. Messi,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini
Neymar Jr,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior

In [93]:
column=[1,2,3,4]
df.iloc[0:10,column]

,player_url,long_name,age,dob
short_name,,,,
L. Messi,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24
Cristiano Ronaldo,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05
Neymar Jr,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05
J. Oblak,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07
E. Hazard,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07
K. De Bruyne,https://sofifa.com/player/192985/kevin-de-bruy...,Kevin De Bruyne,28,1991-06-28
M. ter Stegen,https://sofifa.com/player/192448/marc-andre-te...,Marc-André ter Stegen,27,1992-04-30
V. van Dijk,https://sofifa.com/player/203376/virgil-van-di...,Virgil van Dijk,27,1991-07-08
L. Modrić,https://sofifa.com/player/177003/luka-modric/2...,Luka Modrić,33,1985-09-09
M. Salah,https://sofifa.com/player/209331/mohamed-salah...,Mohamed Salah Ghaly,27,1992-06-15

Selecting with conditions

In [96]:
#select player with heightabove 180 cm
column=[1,2,3,4]
df.iloc[list(df['height_cm']>180),column]

,player_url,long_name,age,dob
short_name,,,,
Cristiano Ronaldo,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05
J. Oblak,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07
K. De Bruyne,https://sofifa.com/player/192985/kevin-de-bruy...,Kevin De Bruyne,28,1991-06-28
M. ter Stegen,https://sofifa.com/player/192448/marc-andre-te...,Marc-André ter Stegen,27,1992-04-30
V. van Dijk,https://sofifa.com/player/203376/virgil-van-di...,Virgil van Dijk,27,1991-07-08
...,...,...,...,...
P. Martin,https://sofifa.com/player/251789/paul-martin/2...,Paul Martin,20,1999-01-05
Shao Shuai,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10
Zhang Wei,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16
Wang Haijian,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02
Pan Ximing,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11

In [100]:
#multiple conditions = from particular country
df.iloc[list((df['height_cm']>180)&(df['nationality']=='Argentina')), :]

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
M. Icardi,201399,https://sofifa.com/player/201399/mauro-icardi/...,Mauro Emanuel Icardi Rivero,26,1993-02-19,181,75,Argentina,Inter,85,...,53+3,52+3,52+3,52+3,53+3,51+3,50+3,50+3,50+3,51+3
G. Higuaín,167664,https://sofifa.com/player/167664/gonzalo-higua...,Gonzalo Gerardo Higuaín,31,1987-12-10,186,89,Argentina,Juventus,85,...,53+3,52+3,52+3,52+3,53+3,49+3,47+3,47+3,47+3,49+3
E. Garay,170481,https://sofifa.com/player/170481/ezequiel-gara...,Ezequiel Marcelo Garay,32,1986-10-10,189,90,Argentina,Valencia CF,83,...,71+3,76+3,76+3,76+3,71+3,72+3,80+3,80+3,80+3,72+3
N. Otamendi,192366,https://sofifa.com/player/192366/nicolas-otame...,Nicolás Hernán Otamendi,31,1988-02-12,183,81,Argentina,Manchester City,83,...,71+3,77+3,77+3,77+3,71+3,73+3,81+3,81+3,81+3,73+3
G. Rulli,215316,https://sofifa.com/player/215316/geronimo-rull...,Gerónimo Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC,81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
T. Durso,240955,https://sofifa.com/player/240955/tomas-durso/2...,Tomás Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata,54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
J. Hass,247295,https://sofifa.com/player/247295/joaquin-hass/...,Joaquín Hass,21,1998-03-27,186,88,Argentina,Club Atlético Colón,54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
R. Ferrario,245057,https://sofifa.com/player/245057/rafael-ferrar...,Rafael Ferrario,19,2000-04-30,186,76,Argentina,Club Atlético Huracán,53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
L. Finochietto,241099,https://sofifa.com/player/241099/leandro-finoc...,Leandro Finochietto,22,1997-04-25,186,77,Argentina,Argentinos Juniors,53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N. Forastiero,246841,https://sofifa.com/player/246841/nicolas-foras...,Nicolás Forastiero,20,1998-07-16,182,79,Argentina,Argentinos Juniors,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN