In [1]:
import pandas as pd

In [7]:
df=pd.read_csv("https://raw.githubusercontent.com/rishirokde-official/Python-for-Data-Science/refs/heads/main/python-for-data-science-main/05.Data%20Extraction/players_20.csv")

In [21]:
df

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [23]:
df=df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [24]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

Drop Row

In [59]:
#drop row (delete)
df.drop('L. Messi' , axis=0)
#all the rows of messi are deleated
df.drop(index=['L. Messi'])

,long_name,age,dob,height_cm,weight_kg,nationality,club,height
short_name,,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,0.0,0,0.0,0.0,Portugal,Juventus,NaN
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,175.0,68.0,Brazil,Paris Saint-Germain,NaN
J. Oblak,Jan Oblak,0.0,0,0.0,0.0,Slovenia,Atlético Madrid,NaN
E. Hazard,Eden Hazard,0.0,0,0.0,0.0,Belgium,Real Madrid,NaN
K. De Bruyne,Kevin De Bruyne,0.0,0,0.0,0.0,Belgium,Manchester City,NaN
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,0.0,0,0.0,0.0,China PR,Beijing Renhe FC,NaN
Xiao Mingjie,Mingjie Xiao,0.0,0,0.0,0.0,China PR,Shanghai SIPG FC,NaN
Zhang Wei,张威,0.0,0,0.0,0.0,China PR,Hebei China Fortune FC,NaN
Wang Haijian,汪海健,0.0,0,0.0,0.0,China PR,Shanghai Greenland Shenhua FC,NaN
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
#drop two or more rows and update data (inplace=True)
df.drop(['L. Messi','Neymar Jr'],axis=0 , inplace=True)

/tmp/ipykernel_1067/3825608070.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['L. Messi','Neymar Jr'],axis=0 , inplace=True)

In [62]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club,height
short_name,,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,0.0,0,0.0,0.0,Portugal,Juventus,NaN
J. Oblak,Jan Oblak,0.0,0,0.0,0.0,Slovenia,Atlético Madrid,NaN
E. Hazard,Eden Hazard,0.0,0,0.0,0.0,Belgium,Real Madrid,NaN
K. De Bruyne,Kevin De Bruyne,0.0,0,0.0,0.0,Belgium,Manchester City,NaN
M. ter Stegen,Marc-André ter Stegen,0.0,0,0.0,0.0,Germany,FC Barcelona,NaN
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,0.0,0,0.0,0.0,China PR,Beijing Renhe FC,NaN
Xiao Mingjie,Mingjie Xiao,0.0,0,0.0,0.0,China PR,Shanghai SIPG FC,NaN
Zhang Wei,张威,0.0,0,0.0,0.0,China PR,Hebei China Fortune FC,NaN
Wang Haijian,汪海健,0.0,0,0.0,0.0,China PR,Shanghai Greenland Shenhua FC,NaN
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Drop Columns

In [63]:
#drop one column
df.drop('long_name',axis=1)

,age,dob,height_cm,weight_kg,nationality,club,height
short_name,,,,,,,
Cristiano Ronaldo,0.0,0,0.0,0.0,Portugal,Juventus,NaN
J. Oblak,0.0,0,0.0,0.0,Slovenia,Atlético Madrid,NaN
E. Hazard,0.0,0,0.0,0.0,Belgium,Real Madrid,NaN
K. De Bruyne,0.0,0,0.0,0.0,Belgium,Manchester City,NaN
M. ter Stegen,0.0,0,0.0,0.0,Germany,FC Barcelona,NaN
...,...,...,...,...,...,...,...
Shao Shuai,0.0,0,0.0,0.0,China PR,Beijing Renhe FC,NaN
Xiao Mingjie,0.0,0,0.0,0.0,China PR,Shanghai SIPG FC,NaN
Zhang Wei,0.0,0,0.0,0.0,China PR,Hebei China Fortune FC,NaN
Wang Haijian,0.0,0,0.0,0.0,China PR,Shanghai Greenland Shenhua FC,NaN
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
#drop column by its position (last column deleated)
df.drop(df.columns[[-1]],axis=1)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,0.0,0,0.0,0.0,Portugal,Juventus
J. Oblak,Jan Oblak,0.0,0,0.0,0.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,0.0,0,0.0,0.0,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,0.0,0,0.0,0.0,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,0.0,0,0.0,0.0,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,0.0,0,0.0,0.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,0.0,0,0.0,0.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,0.0,0,0.0,0.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,0.0,0,0.0,0.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
# drop two or more columns and update data (inplace=True)
df.drop(['long_name' , 'dob'],axis=1 , inplace=True)

/tmp/ipykernel_1067/1469296269.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['long_name' , 'dob'],axis=1 , inplace=True)

In [67]:
df

,age,height_cm,weight_kg,nationality,club,height
short_name,,,,,,
Cristiano Ronaldo,0.0,0.0,0.0,Portugal,Juventus,NaN
J. Oblak,0.0,0.0,0.0,Slovenia,Atlético Madrid,NaN
E. Hazard,0.0,0.0,0.0,Belgium,Real Madrid,NaN
K. De Bruyne,0.0,0.0,0.0,Belgium,Manchester City,NaN
M. ter Stegen,0.0,0.0,0.0,Germany,FC Barcelona,NaN
...,...,...,...,...,...,...
Shao Shuai,0.0,0.0,0.0,China PR,Beijing Renhe FC,NaN
Xiao Mingjie,0.0,0.0,0.0,China PR,Shanghai SIPG FC,NaN
Zhang Wei,0.0,0.0,0.0,China PR,Hebei China Fortune FC,NaN
Wang Haijian,0.0,0.0,0.0,China PR,Shanghai Greenland Shenhua FC,NaN
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN